SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


UPDATE `skyfire_string` SET `entry` = 1,`content_loc8` = 'Вы должны выбрать персонажа или существо.' WHERE `skyfire_string`.`entry` = 1;
UPDATE `skyfire_string` SET `entry` = 2,`content_loc8` = 'Вы должны выбрать существо.' WHERE `skyfire_string`.`entry` = 2;
UPDATE `skyfire_string` SET `entry` = 8,`content_loc8` = 'Команда %s имеет подкоманды:%s' WHERE `skyfire_string`.`entry` = 8;
UPDATE `skyfire_string` SET `entry` = 9,`content_loc8` = 'Команды доступные вам:' WHERE `skyfire_string`.`entry` = 9;
UPDATE `skyfire_string` SET `entry` = 11,`content_loc8` = 'Уровень вашей учетной записи: %i' WHERE `skyfire_string`.`entry` = 11;
UPDATE `skyfire_string` SET `entry` = 12,`content_loc8` = 'Игроков онлайн: %u (максимум: %u) Игроков в очереди: %u (максимум: %u)' WHERE `skyfire_string`.`entry` = 12;
UPDATE `skyfire_string` SET `entry` = 13,`content_loc8` = 'Продолжительность работы сервера: %s' WHERE `skyfire_string`.`entry` = 13;
UPDATE `skyfire_string` SET `entry` = 16,`content_loc8` = 'На этом сервере есть следующие активные гейм-мастеры' WHERE `skyfire_string`.`entry` = 16;
UPDATE `skyfire_string` SET `entry` = 17,`content_loc8` = 'На этом сервере нет гейм-мастеров вошедших в игру.' WHERE `skyfire_string`.`entry` = 17;
UPDATE `skyfire_string` SET `entry` = 18,`content_loc8` = 'Не могу сделать это в полете.' WHERE `skyfire_string`.`entry` = 18;
UPDATE `skyfire_string` SET `entry` = 19,`content_loc8` = 'Не могу сделать это на Полях битвы.' WHERE `skyfire_string`.`entry` = 19;
UPDATE `skyfire_string` SET `entry` = 20,`content_loc8` = 'Цель летает, вы не можете сделать этого.' WHERE `skyfire_string`.`entry` = 20;
UPDATE `skyfire_string` SET `entry` = 21,`content_loc8` = '%s летает, команда не выполнена.' WHERE `skyfire_string`.`entry` = 21;
UPDATE `skyfire_string` SET `entry` = 22,`content_loc8` = 'Вы не можете слезть с ездового животного, так как вы не на нем.' WHERE `skyfire_string`.`entry` = 22;
UPDATE `skyfire_string` SET `entry` = 23,`content_loc8` = 'Не могу сделать это в бою.' WHERE `skyfire_string`.`entry` = 23;
UPDATE `skyfire_string` SET `entry` = 24,`content_loc8` = 'Вы недавно использовали это.' WHERE `skyfire_string`.`entry` = 24;
UPDATE `skyfire_string` SET `entry` = 25,`content_loc8` = 'Ваш пароль не может быть длиннее 16 знаков(ограничение клиента), пароль не изменен!' WHERE `skyfire_string`.`entry` = 25;
UPDATE `skyfire_string` SET `entry` = 26,`content_loc8` = 'Пароль изменен' WHERE `skyfire_string`.`entry` = 26;
UPDATE `skyfire_string` SET `entry` = 27,`content_loc8` = 'Старый пароль неверен' WHERE `skyfire_string`.`entry` = 27;
UPDATE `skyfire_string` SET `entry` = 28,`content_loc8` = 'Ваша учетная запись сейчас заблокирована.' WHERE `skyfire_string`.`entry` = 28;
UPDATE `skyfire_string` SET `entry` = 29,`content_loc8` = 'Ваша учетная запись сейчас разблокирована.' WHERE `skyfire_string`.`entry` = 29;
UPDATE `skyfire_string` SET `entry` = 30,`content_loc8` = ', ранг ' WHERE `skyfire_string`.`entry` = 30;
UPDATE `skyfire_string` SET `entry` = 31,`content_loc8` = ' [выучено]' WHERE `skyfire_string`.`entry` = 31;
UPDATE `skyfire_string` SET `entry` = 32,`content_loc8` = ' [обучение]' WHERE `skyfire_string`.`entry` = 32;
UPDATE `skyfire_string` SET `entry` = 33,`content_loc8` = ' [пассивный]' WHERE `skyfire_string`.`entry` = 33;
UPDATE `skyfire_string` SET `entry` = 34,`content_loc8` = ' [талант]' WHERE `skyfire_string`.`entry` = 34;
UPDATE `skyfire_string` SET `entry` = 35,`content_loc8` = ' [активный]' WHERE `skyfire_string`.`entry` = 35;
UPDATE `skyfire_string` SET `entry` = 36,`content_loc8` = ' [завершено]' WHERE `skyfire_string`.`entry` = 36;
UPDATE `skyfire_string` SET `entry` = 37,`content_loc8` = ' (не в сети)' WHERE `skyfire_string`.`entry` = 37;
UPDATE `skyfire_string` SET `entry` = 38,`content_loc8` = 'вкл.' WHERE `skyfire_string`.`entry` = 38;
UPDATE `skyfire_string` SET `entry` = 39,`content_loc8` = 'откл.' WHERE `skyfire_string`.`entry` = 39;
UPDATE `skyfire_string` SET `entry` = 40,`content_loc8` = 'Вы: %s' WHERE `skyfire_string`.`entry` = 40;
UPDATE `skyfire_string` SET `entry` = 41,`content_loc8` = 'видимый' WHERE `skyfire_string`.`entry` = 41;
UPDATE `skyfire_string` SET `entry` = 42,`content_loc8` = 'невидимый' WHERE `skyfire_string`.`entry` = 42;
UPDATE `skyfire_string` SET `entry` = 43,`content_loc8` = 'сделано' WHERE `skyfire_string`.`entry` = 43;
UPDATE `skyfire_string` SET `entry` = 44,`content_loc8` = 'Вы' WHERE `skyfire_string`.`entry` = 44;
UPDATE `skyfire_string` SET `entry` = 45,`content_loc8` = ' <неизвестный> ' WHERE `skyfire_string`.`entry` = 45;
UPDATE `skyfire_string` SET `entry` = 46,`content_loc8` = '<ошибка>' WHERE `skyfire_string`.`entry` = 46;
UPDATE `skyfire_string` SET `entry` = 47,`content_loc8` = '<не существующий персонаж>' WHERE `skyfire_string`.`entry` = 47;
UPDATE `skyfire_string` SET `entry` = 48,`content_loc8` = 'НЕИЗВЕСТНЫЙ' WHERE `skyfire_string`.`entry` = 48;
UPDATE `skyfire_string` SET `entry` = 49,`content_loc8` = 'Необходимо быть не менее %u уровня, чтобы войти.' WHERE `skyfire_string`.`entry` = 49;
UPDATE `skyfire_string` SET `entry` = 50,`content_loc8` = 'Необходимо быть не менее %u уровня и иметь предмет %s чтобы войти.' WHERE `skyfire_string`.`entry` = 50;
UPDATE `skyfire_string` SET `entry` = 51,`content_loc8` = 'Привет! Готовы к обучению?' WHERE `skyfire_string`.`entry` = 51;
UPDATE `skyfire_string` SET `entry` = 52,`content_loc8` = 'Неверное количество предметов (%u) для предмета %u' WHERE `skyfire_string`.`entry` = 52;
UPDATE `skyfire_string` SET `entry` = 53,`content_loc8` = 'У почты не может быть больше %u ячеек для предметов' WHERE `skyfire_string`.`entry` = 53;
UPDATE `skyfire_string` SET `entry` = 54,`content_loc8` = 'Новые пароли не совпадают' WHERE `skyfire_string`.`entry` = 54;
UPDATE `skyfire_string` SET `entry` = 55,`content_loc8` = 'Ваш пароль не может быть длиннее 16 символов (предел клиента), пароль не изменен!' WHERE `skyfire_string`.`entry` = 55;
UPDATE `skyfire_string` SET `entry` = 56,`content_loc8` = 'Текущее сообщение дня: %s' WHERE `skyfire_string`.`entry` = 56;
UPDATE `skyfire_string` SET `entry` = 57,`content_loc8` = 'Используемая База Данных: %s' WHERE `skyfire_string`.`entry` = 57;
UPDATE `skyfire_string` SET `entry` = 58,`content_loc8` = 'Используемая библиотека скриптов: %s' WHERE `skyfire_string`.`entry` = 58;
UPDATE `skyfire_string` SET `entry` = 59,`content_loc8` = 'Название и версия EventAI: %s' WHERE `skyfire_string`.`entry` = 59;
UPDATE `skyfire_string` SET `entry` = 60,`content_loc8` = 'Онлайн игроков: %u (максимум: %u)' WHERE `skyfire_string`.`entry` = 60;
UPDATE `skyfire_string` SET `entry` = 61,`content_loc8` = 'Разрешенная версия аддона игры %u.' WHERE `skyfire_string`.`entry` = 61;
UPDATE `skyfire_string` SET `entry` = 100,`content_loc8` = 'Глобальное сообщение: ' WHERE `skyfire_string`.`entry` = 100;
UPDATE `skyfire_string` SET `entry` = 101,`content_loc8` = 'Карта: %u (%s) Зона: %u (%s) Область: %u (%s) Фаза: %u\nX: %f Y: %f Z: %f Ориентация: %f\nсетка[%u,%u]ячейка[%u,%u] ИНИнстанса: %u\n XЗоны: %f YЗоны: %f\nZОснования: %f ZПола: %f имеете данные Высот (Карта: %u КартаВ: %u)' WHERE `skyfire_string`.`entry` = 101;
UPDATE `skyfire_string` SET `entry` = 102,`content_loc8` = '%s уже телепортируется.' WHERE `skyfire_string`.`entry` = 102;
UPDATE `skyfire_string` SET `entry` = 103,`content_loc8` = 'Вы можете призвать игрока в Ваше подземелье, только если он в Вашей группе, а Вы лидер группы.' WHERE `skyfire_string`.`entry` = 103;
UPDATE `skyfire_string` SET `entry` = 104,`content_loc8` = 'Вы не можете отправиться к игроку в подземелье, потому что Вы сейчас в группе.' WHERE `skyfire_string`.`entry` = 104;
UPDATE `skyfire_string` SET `entry` = 105,`content_loc8` = 'Вы можете отправиться в подземелье игрока, не находясь в его группе, только с включенным GM режимом.' WHERE `skyfire_string`.`entry` = 105;
UPDATE `skyfire_string` SET `entry` = 106,`content_loc8` = 'Вы не можете отправиться к игроку %s из подземелья в подземелье.' WHERE `skyfire_string`.`entry` = 106;
UPDATE `skyfire_string` SET `entry` = 107,`content_loc8` = 'Вы не можете призвать игрока %s из подземелья в подземелье.' WHERE `skyfire_string`.`entry` = 107;
UPDATE `skyfire_string` SET `entry` = 108,`content_loc8` = 'Вы призываете %s%s.' WHERE `skyfire_string`.`entry` = 108;
UPDATE `skyfire_string` SET `entry` = 109,`content_loc8` = 'Вас призывает %s.' WHERE `skyfire_string`.`entry` = 109;
UPDATE `skyfire_string` SET `entry` = 110,`content_loc8` = 'Вы телепортируйте %s%s к %s.' WHERE `skyfire_string`.`entry` = 110;
UPDATE `skyfire_string` SET `entry` = 111,`content_loc8` = 'Вас телепортирует %s.' WHERE `skyfire_string`.`entry` = 111;
UPDATE `skyfire_string` SET `entry` = 112,`content_loc8` = 'Игрока (%s) не существует.' WHERE `skyfire_string`.`entry` = 112;
UPDATE `skyfire_string` SET `entry` = 113,`content_loc8` = 'Появление в местоположении %s.' WHERE `skyfire_string`.`entry` = 113;
UPDATE `skyfire_string` SET `entry` = 114,`content_loc8` = '%s появляется около вас.' WHERE `skyfire_string`.`entry` = 114;
UPDATE `skyfire_string` SET `entry` = 115,`content_loc8` = 'Неверные значения.' WHERE `skyfire_string`.`entry` = 115;
UPDATE `skyfire_string` SET `entry` = 116,`content_loc8` = 'Персонаж не выбран.' WHERE `skyfire_string`.`entry` = 116;
UPDATE `skyfire_string` SET `entry` = 117,`content_loc8` = '%s не в группе.' WHERE `skyfire_string`.`entry` = 117;
UPDATE `skyfire_string` SET `entry` = 118,`content_loc8` = 'Вы установили запас здоровья %s до %i/%i.' WHERE `skyfire_string`.`entry` = 118;
UPDATE `skyfire_string` SET `entry` = 119,`content_loc8` = '%s установил запас вашего здоровья до %i/%i.' WHERE `skyfire_string`.`entry` = 119;
UPDATE `skyfire_string` SET `entry` = 120,`content_loc8` = 'Вы установили запас маны %s до %i/%i.' WHERE `skyfire_string`.`entry` = 120;
UPDATE `skyfire_string` SET `entry` = 121,`content_loc8` = '%s установил запас Вашей маны до %i/%i.' WHERE `skyfire_string`.`entry` = 121;
UPDATE `skyfire_string` SET `entry` = 122,`content_loc8` = 'Вы установили запас энергии %s до %i/%i.' WHERE `skyfire_string`.`entry` = 122;
UPDATE `skyfire_string` SET `entry` = 123,`content_loc8` = '%s установил запас вашей энергии до %i/%i.' WHERE `skyfire_string`.`entry` = 123;
UPDATE `skyfire_string` SET `entry` = 124,`content_loc8` = 'Текущая энергия: %u' WHERE `skyfire_string`.`entry` = 124;
UPDATE `skyfire_string` SET `entry` = 125,`content_loc8` = 'Вы установили запас ярости %s до %i/%i.' WHERE `skyfire_string`.`entry` = 125;
UPDATE `skyfire_string` SET `entry` = 126,`content_loc8` = '%s установил запас вашей ярости до %i/%i.' WHERE `skyfire_string`.`entry` = 126;
UPDATE `skyfire_string` SET `entry` = 127,`content_loc8` = 'Вы установили уровень %s до %i.' WHERE `skyfire_string`.`entry` = 127;
UPDATE `skyfire_string` SET `entry` = 128,`content_loc8` = 'GUID %i, фракция %i, флаги %i, нипфлаги %i, DY флаг %i' WHERE `skyfire_string`.`entry` = 128;
UPDATE `skyfire_string` SET `entry` = 129,`content_loc8` = 'Неверная фракция: %u (не найдено в factiontemplate.dbc).' WHERE `skyfire_string`.`entry` = 129;
UPDATE `skyfire_string` SET `entry` = 130,`content_loc8` = 'Вы установили GUID=%i Фракцию на %i, флаги на %i, нипфлаги на %i, дyфлаги на %i.' WHERE `skyfire_string`.`entry` = 130;
UPDATE `skyfire_string` SET `entry` = 131,`content_loc8` = 'Вы установили spellflatid=%i, знач= %i, метка =%i на %s.' WHERE `skyfire_string`.`entry` = 131;
UPDATE `skyfire_string` SET `entry` = 132,`content_loc8` = '%s установил Ваш spellflatid=%i, знач= %i, mark =%i.' WHERE `skyfire_string`.`entry` = 132;
UPDATE `skyfire_string` SET `entry` = 133,`content_loc8` = '%s получил сейчас доступ ко всем маршрутным путям (до Выхода).' WHERE `skyfire_string`.`entry` = 133;
UPDATE `skyfire_string` SET `entry` = 134,`content_loc8` = '%s больше не имеет доступа ко всем маршрутным путям (только посещенные доступны).' WHERE `skyfire_string`.`entry` = 134;
UPDATE `skyfire_string` SET `entry` = 135,`content_loc8` = '%s дал вам доступ ко всем маршрутным путям (до Выхода).' WHERE `skyfire_string`.`entry` = 135;
UPDATE `skyfire_string` SET `entry` = 136,`content_loc8` = '%s убрал доступ ко всем маршрутным путям (только посещенные все еще доступны).' WHERE `skyfire_string`.`entry` = 136;
UPDATE `skyfire_string` SET `entry` = 137,`content_loc8` = 'Вы установили все скорости на %2.2f от нормальной у %s.' WHERE `skyfire_string`.`entry` = 137;
UPDATE `skyfire_string` SET `entry` = 138,`content_loc8` = '%s установил все ваши скорости на %2.2f от нормальной.' WHERE `skyfire_string`.`entry` = 138;
UPDATE `skyfire_string` SET `entry` = 139,`content_loc8` = 'Вы установили скорость на %2.2f от нормальной у %s.' WHERE `skyfire_string`.`entry` = 139;
UPDATE `skyfire_string` SET `entry` = 140,`content_loc8` = '%s установил вашу скорость на %2.2f от нормальной.' WHERE `skyfire_string`.`entry` = 140;
UPDATE `skyfire_string` SET `entry` = 141,`content_loc8` = 'Вы установили скорость плавания на %2.2f от нормальной у %s.' WHERE `skyfire_string`.`entry` = 141;
UPDATE `skyfire_string` SET `entry` = 142,`content_loc8` = '%s установил вашу скорость плавания на %2.2f от нормальной.' WHERE `skyfire_string`.`entry` = 142;
UPDATE `skyfire_string` SET `entry` = 143,`content_loc8` = 'Вы установил скорость передвижения назад на %2.2f от нормальной у %s.' WHERE `skyfire_string`.`entry` = 143;
UPDATE `skyfire_string` SET `entry` = 144,`content_loc8` = '%s установил вашу скорость передвижения назад на  %2.2f от нормальной.' WHERE `skyfire_string`.`entry` = 144;
UPDATE `skyfire_string` SET `entry` = 145,`content_loc8` = 'Вы установили скорость полета на %2.2f от нормальной у %s.' WHERE `skyfire_string`.`entry` = 145;
UPDATE `skyfire_string` SET `entry` = 146,`content_loc8` = '%s установил вашу скорость полета на %2.2f от нормальной.' WHERE `skyfire_string`.`entry` = 146;
UPDATE `skyfire_string` SET `entry` = 147,`content_loc8` = 'Вы установили размер на %2.2f у %s.' WHERE `skyfire_string`.`entry` = 147;
UPDATE `skyfire_string` SET `entry` = 148,`content_loc8` = '%s установил ваш размер на %2.2f.' WHERE `skyfire_string`.`entry` = 148;
UPDATE `skyfire_string` SET `entry` = 149,`content_loc8` = 'Такое ездовое животное отсутствует.' WHERE `skyfire_string`.`entry` = 149;
UPDATE `skyfire_string` SET `entry` = 150,`content_loc8` = 'Вы отдали свое ездовое животное %s.' WHERE `skyfire_string`.`entry` = 150;
UPDATE `skyfire_string` SET `entry` = 151,`content_loc8` = '%s отдал Вам свое ездовое животное.' WHERE `skyfire_string`.`entry` = 151;
UPDATE `skyfire_string` SET `entry` = 152,`content_loc8` = 'ПОЛЬЗОВАТЕЛЬ1: %i, ДОБАВИТЬ: %i, РАЗНИЦА: %i' WHERE `skyfire_string`.`entry` = 152;
UPDATE `skyfire_string` SET `entry` = 153,`content_loc8` = 'Вы взяли всю медь у %s.' WHERE `skyfire_string`.`entry` = 153;
UPDATE `skyfire_string` SET `entry` = 154,`content_loc8` = '%s взял всю вашу медь.' WHERE `skyfire_string`.`entry` = 154;
UPDATE `skyfire_string` SET `entry` = 155,`content_loc8` = 'Вы взяли %i меди у %s.' WHERE `skyfire_string`.`entry` = 155;
UPDATE `skyfire_string` SET `entry` = 156,`content_loc8` = '%s взял %i меди у вас.' WHERE `skyfire_string`.`entry` = 156;
UPDATE `skyfire_string` SET `entry` = 157,`content_loc8` = 'Вы дали %i меди %s.' WHERE `skyfire_string`.`entry` = 157;
UPDATE `skyfire_string` SET `entry` = 158,`content_loc8` = '%s дал вам %i меди.' WHERE `skyfire_string`.`entry` = 158;
UPDATE `skyfire_string` SET `entry` = 159,`content_loc8` = 'Вы слышите звук %u.' WHERE `skyfire_string`.`entry` = 159;
UPDATE `skyfire_string` SET `entry` = 160,`content_loc8` = 'ПОЛЬЗОВАТЕЛЬ2: %i, ДОБАВИТЬ: %i, РЕЗУЛЬТАТ: %i' WHERE `skyfire_string`.`entry` = 160;
UPDATE `skyfire_string` SET `entry` = 161,`content_loc8` = 'Удален бит(двоичный разряд) %i в поле %i.' WHERE `skyfire_string`.`entry` = 161;
UPDATE `skyfire_string` SET `entry` = 162,`content_loc8` = 'Добавлен бит(двоичный разряд) %i в поле %i.' WHERE `skyfire_string`.`entry` = 162;
UPDATE `skyfire_string` SET `entry` = 163,`content_loc8` = 'Таблица локаций для телепортации пуста.' WHERE `skyfire_string`.`entry` = 163;
UPDATE `skyfire_string` SET `entry` = 164,`content_loc8` = 'Локация для телепортации не найдена!' WHERE `skyfire_string`.`entry` = 164;
UPDATE `skyfire_string` SET `entry` = 165,`content_loc8` = 'Требуется параметр поиска.' WHERE `skyfire_string`.`entry` = 165;
UPDATE `skyfire_string` SET `entry` = 166,`content_loc8` = 'Нет подходящих вашему запросу локаций для телепортации.' WHERE `skyfire_string`.`entry` = 166;
UPDATE `skyfire_string` SET `entry` = 168,`content_loc8` = 'Найденные локации:\r\n%s' WHERE `skyfire_string`.`entry` = 168;
UPDATE `skyfire_string` SET `entry` = 169,`content_loc8` = 'Письмо отправлено к %s' WHERE `skyfire_string`.`entry` = 169;
UPDATE `skyfire_string` SET `entry` = 170,`content_loc8` = 'Вы пытаетесь прослушать звук %u но такого не существует.' WHERE `skyfire_string`.`entry` = 170;
UPDATE `skyfire_string` SET `entry` = 171,`content_loc8` = 'Вы не можете телепортировать себя к себе!' WHERE `skyfire_string`.`entry` = 171;
UPDATE `skyfire_string` SET `entry` = 172,`content_loc8` = 'команда консоли сервера' WHERE `skyfire_string`.`entry` = 172;
UPDATE `skyfire_string` SET `entry` = 173,`content_loc8` = 'Вы установили запас силы рун %s до %i/%i.' WHERE `skyfire_string`.`entry` = 173;
UPDATE `skyfire_string` SET `entry` = 174,`content_loc8` = '%s установил запас Вашей силы рун до %i/%i.' WHERE `skyfire_string`.`entry` = 174;
UPDATE `skyfire_string` SET `entry` = 175,`content_loc8` = 'Уровень жидкости %f, земля: %f, тип: %d, статус: %d' WHERE `skyfire_string`.`entry` = 175;
UPDATE `skyfire_string` SET `entry` = 200,`content_loc8` = 'Нет выбора.' WHERE `skyfire_string`.`entry` = 200;
UPDATE `skyfire_string` SET `entry` = 201,`content_loc8` = 'GUID объекта: младшие биты %u старшие биты %X' WHERE `skyfire_string`.`entry` = 201;
UPDATE `skyfire_string` SET `entry` = 202,`content_loc8` = 'Слишком длинное имя из %i знаков.' WHERE `skyfire_string`.`entry` = 202;
UPDATE `skyfire_string` SET `entry` = 203,`content_loc8` = 'Ошибка, имя может содержать только знаки алфавита.' WHERE `skyfire_string`.`entry` = 203;
UPDATE `skyfire_string` SET `entry` = 204,`content_loc8` = 'Слишком длинное подимя из %i знаков.' WHERE `skyfire_string`.`entry` = 204;
UPDATE `skyfire_string` SET `entry` = 205,`content_loc8` = 'Пока не реализовано' WHERE `skyfire_string`.`entry` = 205;
UPDATE `skyfire_string` SET `entry` = 206,`content_loc8` = 'Предмет ''%i'' ''%s'' добавлен в список с макс. количеством ''%i'' и инкр. временем ''%i'' и доп. ценой ''%i''' WHERE `skyfire_string`.`entry` = 206;
UPDATE `skyfire_string` SET `entry` = 207,`content_loc8` = 'Предмет ''%i'' не найден в базе.' WHERE `skyfire_string`.`entry` = 207;
UPDATE `skyfire_string` SET `entry` = 208,`content_loc8` = 'Предмет ''%i'' ''%s'' удален из списка торговца' WHERE `skyfire_string`.`entry` = 208;
UPDATE `skyfire_string` SET `entry` = 209,`content_loc8` = 'Предмет ''%i'' не найден в списке торговца.' WHERE `skyfire_string`.`entry` = 209;
UPDATE `skyfire_string` SET `entry` = 210,`content_loc8` = 'Предмет ''%i'' уже в списке торговца.' WHERE `skyfire_string`.`entry` = 210;
UPDATE `skyfire_string` SET `entry` = 211,`content_loc8` = 'Сброс заклинаний у %s.' WHERE `skyfire_string`.`entry` = 211;
UPDATE `skyfire_string` SET `entry` = 212,`content_loc8` = 'Сброс заклинаний у %s при следующем входе.' WHERE `skyfire_string`.`entry` = 212;
UPDATE `skyfire_string` SET `entry` = 213,`content_loc8` = 'Сброс талантов у %s.' WHERE `skyfire_string`.`entry` = 213;
UPDATE `skyfire_string` SET `entry` = 214,`content_loc8` = 'Сброс талантов %s при следующем входе.' WHERE `skyfire_string`.`entry` = 214;
UPDATE `skyfire_string` SET `entry` = 215,`content_loc8` = 'Ваши заклинания были сброшены.' WHERE `skyfire_string`.`entry` = 215;
UPDATE `skyfire_string` SET `entry` = 216,`content_loc8` = 'Ваши таланты были сброшены.' WHERE `skyfire_string`.`entry` = 216;
UPDATE `skyfire_string` SET `entry` = 217,`content_loc8` = 'Неизвестное значение ''%s'' для команды .reset all Напечатайте полное правильное имя.' WHERE `skyfire_string`.`entry` = 217;
UPDATE `skyfire_string` SET `entry` = 218,`content_loc8` = 'Сброс заклинаний для всех игроков при входе. Настоятельно рекомендуем перезайти!' WHERE `skyfire_string`.`entry` = 218;
UPDATE `skyfire_string` SET `entry` = 219,`content_loc8` = 'Сброс талантов для всех игроков при входе. Настоятельно рекомендуем перезайти!' WHERE `skyfire_string`.`entry` = 219;
UPDATE `skyfire_string` SET `entry` = 220,`content_loc8` = 'Существо (GUID: %u) Не найдено точек пути.' WHERE `skyfire_string`.`entry` = 220;
UPDATE `skyfire_string` SET `entry` = 221,`content_loc8` = 'Существо (GUID: %u) Последняя точка пути не найдена.' WHERE `skyfire_string`.`entry` = 221;
UPDATE `skyfire_string` SET `entry` = 222,`content_loc8` = 'Существо (GUID: %u) Не найдено точек пути - использовано ''wpguid''. Поиск по его позиции...' WHERE `skyfire_string`.`entry` = 222;
UPDATE `skyfire_string` SET `entry` = 223,`content_loc8` = 'Существо (GUID: %u) Не найдено точек пути - Это проблема базы MaNGOS (одиночный float).' WHERE `skyfire_string`.`entry` = 223;
UPDATE `skyfire_string` SET `entry` = 224,`content_loc8` = 'Выбранное существо проигнорировано -  использован предоставленный GUID' WHERE `skyfire_string`.`entry` = 224;
UPDATE `skyfire_string` SET `entry` = 225,`content_loc8` = 'Существо (GUID: %u) не найдено' WHERE `skyfire_string`.`entry` = 225;
UPDATE `skyfire_string` SET `entry` = 226,`content_loc8` = 'Вы должны выбрать визуальную точку пути.' WHERE `skyfire_string`.`entry` = 226;
UPDATE `skyfire_string` SET `entry` = 227,`content_loc8` = 'Не найдено точек пути' WHERE `skyfire_string`.`entry` = 227;
UPDATE `skyfire_string` SET `entry` = 228,`content_loc8` = 'Невозможно создать визуальную точку пути с ID существа: %d' WHERE `skyfire_string`.`entry` = 228;
UPDATE `skyfire_string` SET `entry` = 229,`content_loc8` = 'Все визуальные точки пути убраны' WHERE `skyfire_string`.`entry` = 229;
UPDATE `skyfire_string` SET `entry` = 230,`content_loc8` = 'Невозможно создать точку пути с ID: %d' WHERE `skyfire_string`.`entry` = 230;
UPDATE `skyfire_string` SET `entry` = 231,`content_loc8` = 'Не предоставлено GUID.' WHERE `skyfire_string`.`entry` = 231;
UPDATE `skyfire_string` SET `entry` = 232,`content_loc8` = 'Не предоставлен номер точки пути.' WHERE `skyfire_string`.`entry` = 232;
UPDATE `skyfire_string` SET `entry` = 233,`content_loc8` = 'Требуется аргумент для ''%s''.' WHERE `skyfire_string`.`entry` = 233;
UPDATE `skyfire_string` SET `entry` = 234,`content_loc8` = 'Точка пути %i добавлена к GUID: %d' WHERE `skyfire_string`.`entry` = 234;
UPDATE `skyfire_string` SET `entry` = 235,`content_loc8` = 'Точка пути %d добавлена.' WHERE `skyfire_string`.`entry` = 235;
UPDATE `skyfire_string` SET `entry` = 236,`content_loc8` = 'Точка пути изменена.' WHERE `skyfire_string`.`entry` = 236;
UPDATE `skyfire_string` SET `entry` = 237,`content_loc8` = 'Точка пути %s модифицирована.' WHERE `skyfire_string`.`entry` = 237;
UPDATE `skyfire_string` SET `entry` = 238,`content_loc8` = 'Экспорт ТП успешно завершен.' WHERE `skyfire_string`.`entry` = 238;
UPDATE `skyfire_string` SET `entry` = 239,`content_loc8` = 'Не найдено точек пути.' WHERE `skyfire_string`.`entry` = 239;
UPDATE `skyfire_string` SET `entry` = 240,`content_loc8` = 'Файл импортирован.' WHERE `skyfire_string`.`entry` = 240;
UPDATE `skyfire_string` SET `entry` = 241,`content_loc8` = 'Точка пути убрана.' WHERE `skyfire_string`.`entry` = 241;
UPDATE `skyfire_string` SET `entry` = 242,`content_loc8` = 'Предупреждение: Невозможно удалить точку пути из мира с ID: %d' WHERE `skyfire_string`.`entry` = 242;
UPDATE `skyfire_string` SET `entry` = 243,`content_loc8` = 'Это происходит, если точка пути слишком далеко от вашего персонажа.' WHERE `skyfire_string`.`entry` = 243;
UPDATE `skyfire_string` SET `entry` = 244,`content_loc8` = 'ТП удалена из базы, но не из мира.' WHERE `skyfire_string`.`entry` = 244;
UPDATE `skyfire_string` SET `entry` = 245,`content_loc8` = 'Они исчезнут после перезапуска сервера.' WHERE `skyfire_string`.`entry` = 245;
UPDATE `skyfire_string` SET `entry` = 246,`content_loc8` = 'Точка пути %d: Информация для существа: %s, GUID: %d' WHERE `skyfire_string`.`entry` = 246;
UPDATE `skyfire_string` SET `entry` = 247,`content_loc8` = 'Время ожидания: %d' WHERE `skyfire_string`.`entry` = 247;
UPDATE `skyfire_string` SET `entry` = 248,`content_loc8` = 'Модель %d: %d' WHERE `skyfire_string`.`entry` = 248;
UPDATE `skyfire_string` SET `entry` = 249,`content_loc8` = 'Эмоция: %d' WHERE `skyfire_string`.`entry` = 249;
UPDATE `skyfire_string` SET `entry` = 250,`content_loc8` = 'Заклинание: %d' WHERE `skyfire_string`.`entry` = 250;
UPDATE `skyfire_string` SET `entry` = 251,`content_loc8` = 'Текст%d (ID: %i): %s' WHERE `skyfire_string`.`entry` = 251;
UPDATE `skyfire_string` SET `entry` = 252,`content_loc8` = 'Скрипт ИИ: %s' WHERE `skyfire_string`.`entry` = 252;
UPDATE `skyfire_string` SET `entry` = 253,`content_loc8` = 'Игрок %s будет принудительно переименован при следующем входе.' WHERE `skyfire_string`.`entry` = 253;
UPDATE `skyfire_string` SET `entry` = 254,`content_loc8` = 'Игрок %s (GUID #%u) будет принудительно переименован при следующем входе.' WHERE `skyfire_string`.`entry` = 254;
UPDATE `skyfire_string` SET `entry` = 255,`content_loc8` = 'Точка пути-существо (GUID: %u) не найдено' WHERE `skyfire_string`.`entry` = 255;
UPDATE `skyfire_string` SET `entry` = 256,`content_loc8` = 'Не удается найти существо...' WHERE `skyfire_string`.`entry` = 256;
UPDATE `skyfire_string` SET `entry` = 257,`content_loc8` = 'Тип движения существа выставлен на ''%s'', точки передвижения удалены (любые).' WHERE `skyfire_string`.`entry` = 257;
UPDATE `skyfire_string` SET `entry` = 258,`content_loc8` = 'Тип движения существа выставлен на ''%s'', точки движения не были удалены.' WHERE `skyfire_string`.`entry` = 258;
UPDATE `skyfire_string` SET `entry` = 259,`content_loc8` = 'Неверное значение, используйте on или off' WHERE `skyfire_string`.`entry` = 259;
UPDATE `skyfire_string` SET `entry` = 260,`content_loc8` = 'Значение сохранено.' WHERE `skyfire_string`.`entry` = 260;
UPDATE `skyfire_string` SET `entry` = 261,`content_loc8` = 'Значение сохранено, вы должны перезайти или очистить кэш игры.' WHERE `skyfire_string`.`entry` = 261;
UPDATE `skyfire_string` SET `entry` = 262,`content_loc8` = 'ID арены %u не найден!' WHERE `skyfire_string`.`entry` = 262;
UPDATE `skyfire_string` SET `entry` = 263,`content_loc8` = 'Карта или координаты некорректны (X: %f Y: %f MapId: %u)' WHERE `skyfire_string`.`entry` = 263;
UPDATE `skyfire_string` SET `entry` = 264,`content_loc8` = 'Координаты территории неверны (X: %f Y: %f AreaId: %u)' WHERE `skyfire_string`.`entry` = 264;
UPDATE `skyfire_string` SET `entry` = 265,`content_loc8` = 'Территория %u (%s) - часть подземелья %u (%s)' WHERE `skyfire_string`.`entry` = 265;
UPDATE `skyfire_string` SET `entry` = 266,`content_loc8` = 'Ничего не найдено!' WHERE `skyfire_string`.`entry` = 266;
UPDATE `skyfire_string` SET `entry` = 267,`content_loc8` = 'Объект не найден!' WHERE `skyfire_string`.`entry` = 267;
UPDATE `skyfire_string` SET `entry` = 268,`content_loc8` = 'Существо не найдено!' WHERE `skyfire_string`.`entry` = 268;
UPDATE `skyfire_string` SET `entry` = 269,`content_loc8` = 'Внимание: Существо найдено не один раз - вы будете перемещены к первому найденному в базе.' WHERE `skyfire_string`.`entry` = 269;
UPDATE `skyfire_string` SET `entry` = 270,`content_loc8` = 'Существо удалено.' WHERE `skyfire_string`.`entry` = 270;
UPDATE `skyfire_string` SET `entry` = 271,`content_loc8` = 'Существо перемещено.' WHERE `skyfire_string`.`entry` = 271;
UPDATE `skyfire_string` SET `entry` = 272,`content_loc8` = 'Существо (GUID:%u) должно быть на той же карте, что и игрок!' WHERE `skyfire_string`.`entry` = 272;
UPDATE `skyfire_string` SET `entry` = 273,`content_loc8` = 'Игровой объект (GUID: %u) не найден' WHERE `skyfire_string`.`entry` = 273;
UPDATE `skyfire_string` SET `entry` = 274,`content_loc8` = 'Игровой объект (GUID: %u) имеет ссылки на не найдённое существо %u в листе игровых объектов и не может быть удалён.' WHERE `skyfire_string`.`entry` = 274;
UPDATE `skyfire_string` SET `entry` = 275,`content_loc8` = 'Игровой объект (GUID: %u) удален' WHERE `skyfire_string`.`entry` = 275;
UPDATE `skyfire_string` SET `entry` = 276,`content_loc8` = 'Игровой объект |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) сдвинут' WHERE `skyfire_string`.`entry` = 276;
UPDATE `skyfire_string` SET `entry` = 277,`content_loc8` = 'Игровой объект |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) перемещён' WHERE `skyfire_string`.`entry` = 277;
UPDATE `skyfire_string` SET `entry` = 278,`content_loc8` = 'Вы должны выбрать продавца' WHERE `skyfire_string`.`entry` = 278;
UPDATE `skyfire_string` SET `entry` = 279,`content_loc8` = 'Вы должны написать ID для предмета' WHERE `skyfire_string`.`entry` = 279;
UPDATE `skyfire_string` SET `entry` = 280,`content_loc8` = 'Торговец имеет слишком много предметов (макс. 128)' WHERE `skyfire_string`.`entry` = 280;
UPDATE `skyfire_string` SET `entry` = 281,`content_loc8` = 'Вы не можете кикнуть себя, используйте ''конец сеанса''' WHERE `skyfire_string`.`entry` = 281;
UPDATE `skyfire_string` SET `entry` = 282,`content_loc8` = 'Игрок %s исключен.' WHERE `skyfire_string`.`entry` = 282;
UPDATE `skyfire_string` SET `entry` = 284,`content_loc8` = 'Приём сообщений: %s' WHERE `skyfire_string`.`entry` = 284;
UPDATE `skyfire_string` SET `entry` = 285,`content_loc8` = 'Приём сообщений: включено' WHERE `skyfire_string`.`entry` = 285;
UPDATE `skyfire_string` SET `entry` = 286,`content_loc8` = 'Приём сообщений: выключено' WHERE `skyfire_string`.`entry` = 286;
UPDATE `skyfire_string` SET `entry` = 287,`content_loc8` = 'Существо (GUID: %u) не найдено' WHERE `skyfire_string`.`entry` = 287;
UPDATE `skyfire_string` SET `entry` = 288,`content_loc8` = 'Кол-во заявок: %i  Показывать новые заявки: %s' WHERE `skyfire_string`.`entry` = 288;
UPDATE `skyfire_string` SET `entry` = 289,`content_loc8` = 'Поступила новая заявка от %s' WHERE `skyfire_string`.`entry` = 289;
UPDATE `skyfire_string` SET `entry` = 290,`content_loc8` = 'Заявка от %s (Последний раз редактировалась: %s):\n%s' WHERE `skyfire_string`.`entry` = 290;
UPDATE `skyfire_string` SET `entry` = 291,`content_loc8` = 'Показывать новые заявки: Включено' WHERE `skyfire_string`.`entry` = 291;
UPDATE `skyfire_string` SET `entry` = 292,`content_loc8` = 'Показывать новые заявки: Отключено' WHERE `skyfire_string`.`entry` = 292;
UPDATE `skyfire_string` SET `entry` = 293,`content_loc8` = 'Заявки %i не существует' WHERE `skyfire_string`.`entry` = 293;
UPDATE `skyfire_string` SET `entry` = 294,`content_loc8` = 'Все заявки удалены.' WHERE `skyfire_string`.`entry` = 294;
UPDATE `skyfire_string` SET `entry` = 295,`content_loc8` = 'Заявка персонажа %s удалена.' WHERE `skyfire_string`.`entry` = 295;
UPDATE `skyfire_string` SET `entry` = 296,`content_loc8` = 'Заявка удалена.' WHERE `skyfire_string`.`entry` = 296;
UPDATE `skyfire_string` SET `entry` = 297,`content_loc8` = 'Дистанция спавна изменена на: %f' WHERE `skyfire_string`.`entry` = 297;
UPDATE `skyfire_string` SET `entry` = 298,`content_loc8` = 'Время спавна изменено на: %i' WHERE `skyfire_string`.`entry` = 298;
UPDATE `skyfire_string` SET `entry` = 299,`content_loc8` = 'Значение чести %s сменено на %u!' WHERE `skyfire_string`.`entry` = 299;
UPDATE `skyfire_string` SET `entry` = 300,`content_loc8` = 'Ваш чат заблокирован на %u минут. Причина: %s.' WHERE `skyfire_string`.`entry` = 300;
UPDATE `skyfire_string` SET `entry` = 301,`content_loc8` = 'Вы заблокировали чат %s на %u минут. Причина: %s.' WHERE `skyfire_string`.`entry` = 301;
UPDATE `skyfire_string` SET `entry` = 302,`content_loc8` = 'Чат игрока уже разблокирован.' WHERE `skyfire_string`.`entry` = 302;
UPDATE `skyfire_string` SET `entry` = 303,`content_loc8` = 'Ваш чат теперь разблокирован.' WHERE `skyfire_string`.`entry` = 303;
UPDATE `skyfire_string` SET `entry` = 304,`content_loc8` = 'Вы разблокировали чат %s.' WHERE `skyfire_string`.`entry` = 304;
UPDATE `skyfire_string` SET `entry` = 305,`content_loc8` = 'Фракция %s (%u) Репутация с f %s изменена на %5d!' WHERE `skyfire_string`.`entry` = 305;
UPDATE `skyfire_string` SET `entry` = 306,`content_loc8` = 'Очки арены игрока %s изменены на %u!' WHERE `skyfire_string`.`entry` = 306;
UPDATE `skyfire_string` SET `entry` = 307,`content_loc8` = 'Фракция не найдена!' WHERE `skyfire_string`.`entry` = 307;
UPDATE `skyfire_string` SET `entry` = 308,`content_loc8` = 'Фракция %i не известна!' WHERE `skyfire_string`.`entry` = 308;
UPDATE `skyfire_string` SET `entry` = 309,`content_loc8` = 'Неправильное значение %s' WHERE `skyfire_string`.`entry` = 309;
UPDATE `skyfire_string` SET `entry` = 310,`content_loc8` = 'дельта должна быть между 0 и %d (включительно)' WHERE `skyfire_string`.`entry` = 310;
UPDATE `skyfire_string` SET `entry` = 311,`content_loc8` = '%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE `skyfire_string`.`entry` = 311;
UPDATE `skyfire_string` SET `entry` = 312,`content_loc8` = ' [видимый]' WHERE `skyfire_string`.`entry` = 312;
UPDATE `skyfire_string` SET `entry` = 313,`content_loc8` = ' [в войне]' WHERE `skyfire_string`.`entry` = 313;
UPDATE `skyfire_string` SET `entry` = 314,`content_loc8` = ' [мир]' WHERE `skyfire_string`.`entry` = 314;
UPDATE `skyfire_string` SET `entry` = 315,`content_loc8` = ' [убран]' WHERE `skyfire_string`.`entry` = 315;
UPDATE `skyfire_string` SET `entry` = 316,`content_loc8` = ' [невидимый]' WHERE `skyfire_string`.`entry` = 316;
UPDATE `skyfire_string` SET `entry` = 317,`content_loc8` = ' [не активен]' WHERE `skyfire_string`.`entry` = 317;
UPDATE `skyfire_string` SET `entry` = 318,`content_loc8` = 'Ненавидящее' WHERE `skyfire_string`.`entry` = 318;
UPDATE `skyfire_string` SET `entry` = 319,`content_loc8` = 'Враждебное' WHERE `skyfire_string`.`entry` = 319;
UPDATE `skyfire_string` SET `entry` = 320,`content_loc8` = 'Недружелюбное' WHERE `skyfire_string`.`entry` = 320;
UPDATE `skyfire_string` SET `entry` = 321,`content_loc8` = 'Нейтральное' WHERE `skyfire_string`.`entry` = 321;
UPDATE `skyfire_string` SET `entry` = 322,`content_loc8` = 'Дружелюбное' WHERE `skyfire_string`.`entry` = 322;
UPDATE `skyfire_string` SET `entry` = 323,`content_loc8` = 'Уважительное' WHERE `skyfire_string`.`entry` = 323;
UPDATE `skyfire_string` SET `entry` = 324,`content_loc8` = 'Почтительное' WHERE `skyfire_string`.`entry` = 324;
UPDATE `skyfire_string` SET `entry` = 325,`content_loc8` = 'Восторженное' WHERE `skyfire_string`.`entry` = 325;
UPDATE `skyfire_string` SET `entry` = 326,`content_loc8` = 'Фракция %s (%u) не может иметь репутацию.' WHERE `skyfire_string`.`entry` = 326;
UPDATE `skyfire_string` SET `entry` = 327,`content_loc8` = ' [нет репутации]' WHERE `skyfire_string`.`entry` = 327;
UPDATE `skyfire_string` SET `entry` = 328,`content_loc8` = 'Персонажей на аккаунте %s (ID: %u)' WHERE `skyfire_string`.`entry` = 328;
UPDATE `skyfire_string` SET `entry` = 329,`content_loc8` = '  %s (GUID %u)' WHERE `skyfire_string`.`entry` = 329;
UPDATE `skyfire_string` SET `entry` = 330,`content_loc8` = 'Игрок не найден!' WHERE `skyfire_string`.`entry` = 330;
UPDATE `skyfire_string` SET `entry` = 331,`content_loc8` = 'Максимальная цена предмета %u не существует' WHERE `skyfire_string`.`entry` = 331;
UPDATE `skyfire_string` SET `entry` = 332,`content_loc8` = 'Режим ГМ включен' WHERE `skyfire_string`.`entry` = 332;
UPDATE `skyfire_string` SET `entry` = 333,`content_loc8` = 'Режим ГМ выключен' WHERE `skyfire_string`.`entry` = 333;
UPDATE `skyfire_string` SET `entry` = 334,`content_loc8` = 'ГМ тэг для чата включен' WHERE `skyfire_string`.`entry` = 334;
UPDATE `skyfire_string` SET `entry` = 335,`content_loc8` = 'ГМ тэг для чата выключен' WHERE `skyfire_string`.`entry` = 335;
UPDATE `skyfire_string` SET `entry` = 336,`content_loc8` = 'Вы починили все предметы %s .' WHERE `skyfire_string`.`entry` = 336;
UPDATE `skyfire_string` SET `entry` = 337,`content_loc8` = ' %s починил(а) все ваши предметы.' WHERE `skyfire_string`.`entry` = 337;
UPDATE `skyfire_string` SET `entry` = 338,`content_loc8` = 'Вы включили режим хождения по воде %s для %s.' WHERE `skyfire_string`.`entry` = 338;
UPDATE `skyfire_string` SET `entry` = 339,`content_loc8` = 'Вам включил(а) режим хождения по воде %s  %s.' WHERE `skyfire_string`.`entry` = 339;
UPDATE `skyfire_string` SET `entry` = 340,`content_loc8` = '%s теперь следует за вами.' WHERE `skyfire_string`.`entry` = 340;
UPDATE `skyfire_string` SET `entry` = 341,`content_loc8` = '%s перестал следовать за вами.' WHERE `skyfire_string`.`entry` = 341;
UPDATE `skyfire_string` SET `entry` = 342,`content_loc8` = '%s теперь не следует за вами.' WHERE `skyfire_string`.`entry` = 342;
UPDATE `skyfire_string` SET `entry` = 343,`content_loc8` = 'Существо (Entry: %u) не может быть приручено.' WHERE `skyfire_string`.`entry` = 343;
UPDATE `skyfire_string` SET `entry` = 344,`content_loc8` = 'У вас уже есть питомец.' WHERE `skyfire_string`.`entry` = 344;
UPDATE `skyfire_string` SET `entry` = 345,`content_loc8` = 'Изменения игрока %s будет предложено при следующем входе в мир.' WHERE `skyfire_string`.`entry` = 345;
UPDATE `skyfire_string` SET `entry` = 346,`content_loc8` = 'Изменения игрока %s (GUID #%u) будет предложено при следующем входе в мир.' WHERE `skyfire_string`.`entry` = 346;
UPDATE `skyfire_string` SET `entry` = 347,`content_loc8` = 'Маршрут такси ID %u не найден!' WHERE `skyfire_string`.`entry` = 347;
UPDATE `skyfire_string` SET `entry` = 348,`content_loc8` = 'Объект (Entry: %u) имеет некоректные данные и не может быть загружен.' WHERE `skyfire_string`.`entry` = 348;
UPDATE `skyfire_string` SET `entry` = 351,`content_loc8` = 'Званий не найдено!' WHERE `skyfire_string`.`entry` = 351;
UPDATE `skyfire_string` SET `entry` = 352,`content_loc8` = 'Неверный ID звания: %u' WHERE `skyfire_string`.`entry` = 352;
UPDATE `skyfire_string` SET `entry` = 353,`content_loc8` = 'Звание %u (%s) добавлено в список полученных званий игрока %s.' WHERE `skyfire_string`.`entry` = 353;
UPDATE `skyfire_string` SET `entry` = 354,`content_loc8` = 'Звание %u (%s) удалено из списка полученных званий игрока %s.' WHERE `skyfire_string`.`entry` = 354;
UPDATE `skyfire_string` SET `entry` = 400,`content_loc8` = '|cffff0000[Системное сообщение]:|rСкрипты перезагружены' WHERE `skyfire_string`.`entry` = 400;
UPDATE `skyfire_string` SET `entry` = 401,`content_loc8` = 'Вы изменили уровень доступа %s на %i.' WHERE `skyfire_string`.`entry` = 401;
UPDATE `skyfire_string` SET `entry` = 402,`content_loc8` = '%s установил ваш уровень доступа на %i.' WHERE `skyfire_string`.`entry` = 402;
UPDATE `skyfire_string` SET `entry` = 403,`content_loc8` = 'У вас недостаточно прав доступа.' WHERE `skyfire_string`.`entry` = 403;
UPDATE `skyfire_string` SET `entry` = 404,`content_loc8` = 'Передвижение существа запрещено.' WHERE `skyfire_string`.`entry` = 404;
UPDATE `skyfire_string` SET `entry` = 405,`content_loc8` = 'Передвижение существа разрешено.' WHERE `skyfire_string`.`entry` = 405;
UPDATE `skyfire_string` SET `entry` = 406,`content_loc8` = 'Погода не может быть изменена на этой территории.' WHERE `skyfire_string`.`entry` = 406;
UPDATE `skyfire_string` SET `entry` = 407,`content_loc8` = 'Погода отключена на сервере.' WHERE `skyfire_string`.`entry` = 407;
UPDATE `skyfire_string` SET `entry` = 408,`content_loc8` = '%s получил бан на %s. Причина: %s.' WHERE `skyfire_string`.`entry` = 408;
UPDATE `skyfire_string` SET `entry` = 409,`content_loc8` = '%s получил вечный бан за %s.' WHERE `skyfire_string`.`entry` = 409;
UPDATE `skyfire_string` SET `entry` = 410,`content_loc8` = '%s %s не найден' WHERE `skyfire_string`.`entry` = 410;
UPDATE `skyfire_string` SET `entry` = 411,`content_loc8` = '%s разбанен.' WHERE `skyfire_string`.`entry` = 411;
UPDATE `skyfire_string` SET `entry` = 412,`content_loc8` = 'Произошла ошибка удаления бана с %s.' WHERE `skyfire_string`.`entry` = 412;
UPDATE `skyfire_string` SET `entry` = 413,`content_loc8` = 'Нет такой учетной записи.' WHERE `skyfire_string`.`entry` = 413;
UPDATE `skyfire_string` SET `entry` = 414,`content_loc8` = 'Нет такого персонажа.' WHERE `skyfire_string`.`entry` = 414;
UPDATE `skyfire_string` SET `entry` = 415,`content_loc8` = 'Такого IP нет в банлисте.' WHERE `skyfire_string`.`entry` = 415;
UPDATE `skyfire_string` SET `entry` = 416,`content_loc8` = 'Учетная запись %s не может быть забанена' WHERE `skyfire_string`.`entry` = 416;
UPDATE `skyfire_string` SET `entry` = 417,`content_loc8` = 'История банов учетной записи %s:' WHERE `skyfire_string`.`entry` = 417;
UPDATE `skyfire_string` SET `entry` = 418,`content_loc8` = 'Дата бана: %s Время бана: %s Текущее положение: %s  Причина: %s ГМ: %s' WHERE `skyfire_string`.`entry` = 418;
UPDATE `skyfire_string` SET `entry` = 419,`content_loc8` = 'Информация' WHERE `skyfire_string`.`entry` = 419;
UPDATE `skyfire_string` SET `entry` = 420,`content_loc8` = 'Никогда' WHERE `skyfire_string`.`entry` = 420;
UPDATE `skyfire_string` SET `entry` = 421,`content_loc8` = 'Да' WHERE `skyfire_string`.`entry` = 421;
UPDATE `skyfire_string` SET `entry` = 422,`content_loc8` = 'Нет' WHERE `skyfire_string`.`entry` = 422;
UPDATE `skyfire_string` SET `entry` = 423,`content_loc8` = 'IP: %s\nДата запрета: %s\nДата отмены запрета: %s\nОсталось: %s\nПричина: %s\nУстановлена: %s' WHERE `skyfire_string`.`entry` = 423;
UPDATE `skyfire_string` SET `entry` = 424,`content_loc8` = 'Не найден такой забаненный IP.' WHERE `skyfire_string`.`entry` = 424;
UPDATE `skyfire_string` SET `entry` = 425,`content_loc8` = 'Нет подходящей учетной записи.' WHERE `skyfire_string`.`entry` = 425;
UPDATE `skyfire_string` SET `entry` = 426,`content_loc8` = 'Нет забаненого аккаунта, на котором есть такой персонаж.' WHERE `skyfire_string`.`entry` = 426;
UPDATE `skyfire_string` SET `entry` = 427,`content_loc8` = 'Следующие IP совпадают с вашим образцом:' WHERE `skyfire_string`.`entry` = 427;
UPDATE `skyfire_string` SET `entry` = 428,`content_loc8` = 'Следующие учетные записи соответствуют вашему запросу:' WHERE `skyfire_string`.`entry` = 428;
UPDATE `skyfire_string` SET `entry` = 429,`content_loc8` = 'Вы научились всем навыкам/заклинаниям.' WHERE `skyfire_string`.`entry` = 429;
UPDATE `skyfire_string` SET `entry` = 430,`content_loc8` = 'Вы научились всем класовым заклинаниям.' WHERE `skyfire_string`.`entry` = 430;
UPDATE `skyfire_string` SET `entry` = 431,`content_loc8` = 'Вы научились всем класовым навыкам.' WHERE `skyfire_string`.`entry` = 431;
UPDATE `skyfire_string` SET `entry` = 432,`content_loc8` = 'Вы научились всем языкам.' WHERE `skyfire_string`.`entry` = 432;
UPDATE `skyfire_string` SET `entry` = 433,`content_loc8` = 'Вы выучили все профессиональные навыки и рецепты.' WHERE `skyfire_string`.`entry` = 433;
UPDATE `skyfire_string` SET `entry` = 434,`content_loc8` = ' ''%s'' не найден' WHERE `skyfire_string`.`entry` = 434;
UPDATE `skyfire_string` SET `entry` = 435,`content_loc8` = 'Неверный ID предмета: %u' WHERE `skyfire_string`.`entry` = 435;
UPDATE `skyfire_string` SET `entry` = 436,`content_loc8` = 'Не найдено предметов!' WHERE `skyfire_string`.`entry` = 436;
UPDATE `skyfire_string` SET `entry` = 437,`content_loc8` = 'Неверный ID игрового объекта: %u' WHERE `skyfire_string`.`entry` = 437;
UPDATE `skyfire_string` SET `entry` = 438,`content_loc8` = 'Найдено предметов %u: %u ( инвентарь %u почта %u действие %u )' WHERE `skyfire_string`.`entry` = 438;
UPDATE `skyfire_string` SET `entry` = 439,`content_loc8` = 'Найдено игровых объектов %u: %u ' WHERE `skyfire_string`.`entry` = 439;
UPDATE `skyfire_string` SET `entry` = 440,`content_loc8` = 'Неверный ID существа: %u' WHERE `skyfire_string`.`entry` = 440;
UPDATE `skyfire_string` SET `entry` = 441,`content_loc8` = 'Найдено существ %u: %u ' WHERE `skyfire_string`.`entry` = 441;
UPDATE `skyfire_string` SET `entry` = 442,`content_loc8` = 'Не найдено областей!' WHERE `skyfire_string`.`entry` = 442;
UPDATE `skyfire_string` SET `entry` = 443,`content_loc8` = 'Не найдено наборов предметов!' WHERE `skyfire_string`.`entry` = 443;
UPDATE `skyfire_string` SET `entry` = 444,`content_loc8` = 'Не найдено навыков!' WHERE `skyfire_string`.`entry` = 444;
UPDATE `skyfire_string` SET `entry` = 445,`content_loc8` = 'Не найдено заклинаний!' WHERE `skyfire_string`.`entry` = 445;
UPDATE `skyfire_string` SET `entry` = 446,`content_loc8` = 'Не найдено заданий!' WHERE `skyfire_string`.`entry` = 446;
UPDATE `skyfire_string` SET `entry` = 447,`content_loc8` = 'Не найдено существ!' WHERE `skyfire_string`.`entry` = 447;
UPDATE `skyfire_string` SET `entry` = 448,`content_loc8` = 'Не найдено игровых объектов!' WHERE `skyfire_string`.`entry` = 448;
UPDATE `skyfire_string` SET `entry` = 449,`content_loc8` = 'Кладбище #%u не существует.' WHERE `skyfire_string`.`entry` = 449;
UPDATE `skyfire_string` SET `entry` = 450,`content_loc8` = 'Кладбище #%u уже привязано к территории #%u (текущее).' WHERE `skyfire_string`.`entry` = 450;
UPDATE `skyfire_string` SET `entry` = 451,`content_loc8` = 'Кладбище #%u привязано к территории #%u (текущее).' WHERE `skyfire_string`.`entry` = 451;
UPDATE `skyfire_string` SET `entry` = 452,`content_loc8` = 'Кладбище #%u не может быть привязано к подтерритории или не существующей территории #%u (внутренняя ошибка)..' WHERE `skyfire_string`.`entry` = 452;
UPDATE `skyfire_string` SET `entry` = 454,`content_loc8` = 'Нет фракции у кладбища с ID = #%u , исправьте ошибку в базе данных' WHERE `skyfire_string`.`entry` = 454;
UPDATE `skyfire_string` SET `entry` = 455,`content_loc8` = 'неверная команда, проверьте базу данных' WHERE `skyfire_string`.`entry` = 455;
UPDATE `skyfire_string` SET `entry` = 456,`content_loc8` = 'любой' WHERE `skyfire_string`.`entry` = 456;
UPDATE `skyfire_string` SET `entry` = 457,`content_loc8` = 'альянс' WHERE `skyfire_string`.`entry` = 457;
UPDATE `skyfire_string` SET `entry` = 458,`content_loc8` = 'орда' WHERE `skyfire_string`.`entry` = 458;
UPDATE `skyfire_string` SET `entry` = 459,`content_loc8` = 'Кладбище #%u (фракция: %s) ближайшее для привязки к территории #%u.' WHERE `skyfire_string`.`entry` = 459;
UPDATE `skyfire_string` SET `entry` = 460,`content_loc8` = 'У территории #%u нет привязанных к ней кладбищ.' WHERE `skyfire_string`.`entry` = 460;
UPDATE `skyfire_string` SET `entry` = 461,`content_loc8` = 'Территория #%u не имеет привязанных к ней кладбищ для фракции: %s.' WHERE `skyfire_string`.`entry` = 461;
UPDATE `skyfire_string` SET `entry` = 462,`content_loc8` = 'Локация для телепортации уже существует!' WHERE `skyfire_string`.`entry` = 462;
UPDATE `skyfire_string` SET `entry` = 463,`content_loc8` = 'Локация для телепортации добавлена.' WHERE `skyfire_string`.`entry` = 463;
UPDATE `skyfire_string` SET `entry` = 464,`content_loc8` = 'Локация для телепортации не добавлена: ошибка базы.' WHERE `skyfire_string`.`entry` = 464;
UPDATE `skyfire_string` SET `entry` = 465,`content_loc8` = 'Локация для телепортации удалена.' WHERE `skyfire_string`.`entry` = 465;
UPDATE `skyfire_string` SET `entry` = 466,`content_loc8` = 'Не найдено точек полета!' WHERE `skyfire_string`.`entry` = 466;
UPDATE `skyfire_string` SET `entry` = 467,`content_loc8` = 'Выделенная цель имеет %d ауры:' WHERE `skyfire_string`.`entry` = 467;
UPDATE `skyfire_string` SET `entry` = 469,`content_loc8` = 'Выделенная цель имеет %d ауры типов %d:' WHERE `skyfire_string`.`entry` = 469;
UPDATE `skyfire_string` SET `entry` = 470,`content_loc8` = 'ID: %d Эффект: %d Количество: %d' WHERE `skyfire_string`.`entry` = 470;
UPDATE `skyfire_string` SET `entry` = 471,`content_loc8` = 'Задание %u не найдено.' WHERE `skyfire_string`.`entry` = 471;
UPDATE `skyfire_string` SET `entry` = 472,`content_loc8` = 'Квест %u начинается с помощью предмета. Для правильной работы, пожалуйста, положите предмет в инвентарь и начните квест (предмет : .additem %u)' WHERE `skyfire_string`.`entry` = 472;
UPDATE `skyfire_string` SET `entry` = 473,`content_loc8` = 'Задание удалено.' WHERE `skyfire_string`.`entry` = 473;
UPDATE `skyfire_string` SET `entry` = 474,`content_loc8` = ' [вознаграждённый]' WHERE `skyfire_string`.`entry` = 474;
UPDATE `skyfire_string` SET `entry` = 475,`content_loc8` = ' [выполнено]' WHERE `skyfire_string`.`entry` = 475;
UPDATE `skyfire_string` SET `entry` = 476,`content_loc8` = ' [активный]' WHERE `skyfire_string`.`entry` = 476;
UPDATE `skyfire_string` SET `entry` = 477,`content_loc8` = '%s: режим полета %s' WHERE `skyfire_string`.`entry` = 477;
UPDATE `skyfire_string` SET `entry` = 478,`content_loc8` = 'Опкод %u послан %s' WHERE `skyfire_string`.`entry` = 478;
UPDATE `skyfire_string` SET `entry` = 479,`content_loc8` = 'Персонаж успешно загружен!' WHERE `skyfire_string`.`entry` = 479;
UPDATE `skyfire_string` SET `entry` = 480,`content_loc8` = 'Невозможно загрузить персонажа!' WHERE `skyfire_string`.`entry` = 480;
UPDATE `skyfire_string` SET `entry` = 481,`content_loc8` = 'Дамп игрока сохранен!' WHERE `skyfire_string`.`entry` = 481;
UPDATE `skyfire_string` SET `entry` = 482,`content_loc8` = 'Дамп игрока не сделан!' WHERE `skyfire_string`.`entry` = 482;
UPDATE `skyfire_string` SET `entry` = 483,`content_loc8` = 'Заклинание %u не работает и не доступно для применения или изучения!' WHERE `skyfire_string`.`entry` = 483;
UPDATE `skyfire_string` SET `entry` = 484,`content_loc8` = 'Навык %u (%s) игрока %s изменен на %u и текущий максимум стал %u (без permanent (таланты) бонусов).' WHERE `skyfire_string`.`entry` = 484;
UPDATE `skyfire_string` SET `entry` = 485,`content_loc8` = 'Игрок %s должен иметь навык %u (%s), прежде чем использовать эту команду.' WHERE `skyfire_string`.`entry` = 485;
UPDATE `skyfire_string` SET `entry` = 486,`content_loc8` = 'Неверный ID навыка (%u)' WHERE `skyfire_string`.`entry` = 486;
UPDATE `skyfire_string` SET `entry` = 487,`content_loc8` = 'Вы выучили стандартные ГМ заклинания и навыки.' WHERE `skyfire_string`.`entry` = 487;
UPDATE `skyfire_string` SET `entry` = 488,`content_loc8` = 'Вы уже знаете это заклинание.' WHERE `skyfire_string`.`entry` = 488;
UPDATE `skyfire_string` SET `entry` = 489,`content_loc8` = '%s уже знает это заклинание.' WHERE `skyfire_string`.`entry` = 489;
UPDATE `skyfire_string` SET `entry` = 490,`content_loc8` = '%s не знает это заклинание.' WHERE `skyfire_string`.`entry` = 490;
UPDATE `skyfire_string` SET `entry` = 491,`content_loc8` = 'Вы уже забыли это заклинание.' WHERE `skyfire_string`.`entry` = 491;
UPDATE `skyfire_string` SET `entry` = 492,`content_loc8` = 'Перезарядка всех заклинаний у %s завершена.' WHERE `skyfire_string`.`entry` = 492;
UPDATE `skyfire_string` SET `entry` = 493,`content_loc8` = 'Перезарядка заклинания %u у %s завершена.' WHERE `skyfire_string`.`entry` = 493;
UPDATE `skyfire_string` SET `entry` = 494,`content_loc8` = 'Команда : Additem, ID предмета = %i, кол-во = %i' WHERE `skyfire_string`.`entry` = 494;
UPDATE `skyfire_string` SET `entry` = 495,`content_loc8` = 'Команда : Additemset, ID комплекта предметов  = %i' WHERE `skyfire_string`.`entry` = 495;
UPDATE `skyfire_string` SET `entry` = 496,`content_loc8` = 'Предмет (ID = %i, кол-во = %i) убран у %s' WHERE `skyfire_string`.`entry` = 496;
UPDATE `skyfire_string` SET `entry` = 497,`content_loc8` = 'Невозможно создать предмет ''%i'' (кол-во: %i)' WHERE `skyfire_string`.`entry` = 497;
UPDATE `skyfire_string` SET `entry` = 498,`content_loc8` = 'Вы должны ввести имя гильдии!' WHERE `skyfire_string`.`entry` = 498;
UPDATE `skyfire_string` SET `entry` = 499,`content_loc8` = 'Игрок не найден!' WHERE `skyfire_string`.`entry` = 499;
UPDATE `skyfire_string` SET `entry` = 500,`content_loc8` = 'Игрок уже состоит в гильдии!' WHERE `skyfire_string`.`entry` = 500;
UPDATE `skyfire_string` SET `entry` = 501,`content_loc8` = 'Гильдия не создана! (уже существует?)' WHERE `skyfire_string`.`entry` = 501;
UPDATE `skyfire_string` SET `entry` = 502,`content_loc8` = 'Не найдены вещи из набора ''%u''.' WHERE `skyfire_string`.`entry` = 502;
UPDATE `skyfire_string` SET `entry` = 503,`content_loc8` = 'Расстояние: (3D) %f (2D) %f ярд(ов).' WHERE `skyfire_string`.`entry` = 503;
UPDATE `skyfire_string` SET `entry` = 504,`content_loc8` = 'Вещь ''%i'' ''%s'' Слот вещи %i' WHERE `skyfire_string`.`entry` = 504;
UPDATE `skyfire_string` SET `entry` = 505,`content_loc8` = 'Предмет ''%i'' не существует.' WHERE `skyfire_string`.`entry` = 505;
UPDATE `skyfire_string` SET `entry` = 506,`content_loc8` = 'Предмет ''%i'' ''%s'' добавлен в слот %i' WHERE `skyfire_string`.`entry` = 506;
UPDATE `skyfire_string` SET `entry` = 507,`content_loc8` = 'Предмет не сохранен!' WHERE `skyfire_string`.`entry` = 507;
UPDATE `skyfire_string` SET `entry` = 508,`content_loc8` = '%d - владелец: %s (guid: %u аккаунт: %u ) %s' WHERE `skyfire_string`.`entry` = 508;
UPDATE `skyfire_string` SET `entry` = 509,`content_loc8` = '%d - отправитель: %s (guid: %u аккаунт: %u ) получатель: %s (guid: %u аккаунт: %u ) %s' WHERE `skyfire_string`.`entry` = 509;
UPDATE `skyfire_string` SET `entry` = 510,`content_loc8` = '%d - владелец: %s (guid: %u аккаунт: %u ) %s' WHERE `skyfire_string`.`entry` = 510;
UPDATE `skyfire_string` SET `entry` = 511,`content_loc8` = 'Неверный тип ссылки!' WHERE `skyfire_string`.`entry` = 511;
UPDATE `skyfire_string` SET `entry` = 512,`content_loc8` = '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE `skyfire_string`.`entry` = 512;
UPDATE `skyfire_string` SET `entry` = 513,`content_loc8` = '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE `skyfire_string`.`entry` = 513;
UPDATE `skyfire_string` SET `entry` = 514,`content_loc8` = '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE `skyfire_string`.`entry` = 514;
UPDATE `skyfire_string` SET `entry` = 515,`content_loc8` = '%d - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE `skyfire_string`.`entry` = 515;
UPDATE `skyfire_string` SET `entry` = 516,`content_loc8` = '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE `skyfire_string`.`entry` = 516;
UPDATE `skyfire_string` SET `entry` = 518,`content_loc8` = '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE `skyfire_string`.`entry` = 518;
UPDATE `skyfire_string` SET `entry` = 519,`content_loc8` = '|cffffffff|Htele:%s|h[%s]|h|r ' WHERE `skyfire_string`.`entry` = 519;
UPDATE `skyfire_string` SET `entry` = 520,`content_loc8` = '%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE `skyfire_string`.`entry` = 520;
UPDATE `skyfire_string` SET `entry` = 521,`content_loc8` = '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE `skyfire_string`.`entry` = 521;
UPDATE `skyfire_string` SET `entry` = 522,`content_loc8` = 'Игровой объект (GUID: %u) не найден' WHERE `skyfire_string`.`entry` = 522;
UPDATE `skyfire_string` SET `entry` = 523,`content_loc8` = '>> Игровой объект %s (GUID: %u) у %f %f %f. Ориентация %f.' WHERE `skyfire_string`.`entry` = 523;
UPDATE `skyfire_string` SET `entry` = 524,`content_loc8` = 'Выбранный объект: |cffffffff|Hitemset:%d|h[%s]|h|r GUID: %u ID: %u X: %f Y: %f Z: %f MapId: %u Ориентация: %f' WHERE `skyfire_string`.`entry` = 524;
UPDATE `skyfire_string` SET `entry` = 525,`content_loc8` = '>> Добавлен ГО ''%i'' (%s) (GUID: %i) добавлен в ''%f %f %f''.' WHERE `skyfire_string`.`entry` = 525;
UPDATE `skyfire_string` SET `entry` = 540,`content_loc8` = 'Уровень: %u.' WHERE `skyfire_string`.`entry` = 540;
UPDATE `skyfire_string` SET `entry` = 541,`content_loc8` = 'Здоровье (базовое): %u. (максимум): %u. (текущее): %u.' WHERE `skyfire_string`.`entry` = 541;
UPDATE `skyfire_string` SET `entry` = 542,`content_loc8` = 'Флаг цели: %u.\r\nДинамический флаг: %u.\r\nфракция: %u.' WHERE `skyfire_string`.`entry` = 542;
UPDATE `skyfire_string` SET `entry` = 543,`content_loc8` = 'Лут: %u Карманный лут: %u Снятие шкур: %u' WHERE `skyfire_string`.`entry` = 543;
UPDATE `skyfire_string` SET `entry` = 544,`content_loc8` = 'Позиция: %f %f %f.' WHERE `skyfire_string`.`entry` = 544;
UPDATE `skyfire_string` SET `entry` = 545,`content_loc8` = '*** Это продавец!' WHERE `skyfire_string`.`entry` = 545;
UPDATE `skyfire_string` SET `entry` = 546,`content_loc8` = '*** Это тренер!' WHERE `skyfire_string`.`entry` = 546;
UPDATE `skyfire_string` SET `entry` = 547,`content_loc8` = 'ID подземелья: %u' WHERE `skyfire_string`.`entry` = 547;
UPDATE `skyfire_string` SET `entry` = 548,`content_loc8` = 'Игрок %s %s (GUID: %u) Аккаунт: %s (id: %u) Email: %s Уровень доступа: %u Последний IP: %s Последний вход: %s Задержка: %ums' WHERE `skyfire_string`.`entry` = 548;
UPDATE `skyfire_string` SET `entry` = 549,`content_loc8` = 'Раса: %s Класс: %s Игровое время: %s Уровень: %u Деньги: %ug%us%uc' WHERE `skyfire_string`.`entry` = 549;
UPDATE `skyfire_string` SET `entry` = 550,`content_loc8` = 'Команда .pinfo не поддерживает подкоманду ''rep'' для игроков не в сети.' WHERE `skyfire_string`.`entry` = 550;
UPDATE `skyfire_string` SET `entry` = 551,`content_loc8` = '%s открыл все территории.' WHERE `skyfire_string`.`entry` = 551;
UPDATE `skyfire_string` SET `entry` = 552,`content_loc8` = '%s больше не имеет открытых территорий.' WHERE `skyfire_string`.`entry` = 552;
UPDATE `skyfire_string` SET `entry` = 553,`content_loc8` = '%s открыл все территории для Вас.' WHERE `skyfire_string`.`entry` = 553;
UPDATE `skyfire_string` SET `entry` = 554,`content_loc8` = '%s закрыл все открытые территории у Вас.' WHERE `skyfire_string`.`entry` = 554;
UPDATE `skyfire_string` SET `entry` = 555,`content_loc8` = 'Левитация включена' WHERE `skyfire_string`.`entry` = 555;
UPDATE `skyfire_string` SET `entry` = 556,`content_loc8` = 'Левитация выключена' WHERE `skyfire_string`.`entry` = 556;
UPDATE `skyfire_string` SET `entry` = 557,`content_loc8` = '%s повысил вас в уровне до (%i)' WHERE `skyfire_string`.`entry` = 557;
UPDATE `skyfire_string` SET `entry` = 558,`content_loc8` = '%s понизил вас в уровне до (%i)' WHERE `skyfire_string`.`entry` = 558;
UPDATE `skyfire_string` SET `entry` = 559,`content_loc8` = '%s сбросил ваш уровень.' WHERE `skyfire_string`.`entry` = 559;
UPDATE `skyfire_string` SET `entry` = 560,`content_loc8` = 'Территория стала открытой.' WHERE `skyfire_string`.`entry` = 560;
UPDATE `skyfire_string` SET `entry` = 561,`content_loc8` = 'Территория стала закрытой.' WHERE `skyfire_string`.`entry` = 561;
UPDATE `skyfire_string` SET `entry` = 562,`content_loc8` = 'GUID=%i Измененный индекс: %i, значение:  %i.' WHERE `skyfire_string`.`entry` = 562;
UPDATE `skyfire_string` SET `entry` = 563,`content_loc8` = 'Вы изменили у GUID=%i Индекс: %i на значение %i.' WHERE `skyfire_string`.`entry` = 563;
UPDATE `skyfire_string` SET `entry` = 564,`content_loc8` = 'Значение индекса %u слишком большое %u(количество: %u).' WHERE `skyfire_string`.`entry` = 564;
UPDATE `skyfire_string` SET `entry` = 565,`content_loc8` = 'Установить %u uint32 Значение:[OPCODE]:%u [VALUE]:%u' WHERE `skyfire_string`.`entry` = 565;
UPDATE `skyfire_string` SET `entry` = 566,`content_loc8` = 'Вы изменили поле %u Field: %u на uint32 значение: %u' WHERE `skyfire_string`.`entry` = 566;
UPDATE `skyfire_string` SET `entry` = 576,`content_loc8` = 'Изменение значения поля:%u на значение: %u' WHERE `skyfire_string`.`entry` = 576;
UPDATE `skyfire_string` SET `entry` = 577,`content_loc8` = 'Теперь вы невидимы.' WHERE `skyfire_string`.`entry` = 577;
UPDATE `skyfire_string` SET `entry` = 578,`content_loc8` = 'Теперь вы видимы.' WHERE `skyfire_string`.`entry` = 578;
UPDATE `skyfire_string` SET `entry` = 579,`content_loc8` = 'Выбраный игрок или существо не имеет атакуемой цели.' WHERE `skyfire_string`.`entry` = 579;
UPDATE `skyfire_string` SET `entry` = 580,`content_loc8` = 'Игрок %s выучил все стандартные заклинания для расы/класса и получил заклинания, дающиеся за выполнение квестов.' WHERE `skyfire_string`.`entry` = 580;
UPDATE `skyfire_string` SET `entry` = 581,`content_loc8` = 'Поиск ближайших игровых объектов (расстояние %f): %u ' WHERE `skyfire_string`.`entry` = 581;
UPDATE `skyfire_string` SET `entry` = 582,`content_loc8` = 'Время перерождения: Полное:%s Остаток:%s' WHERE `skyfire_string`.`entry` = 582;
UPDATE `skyfire_string` SET `entry` = 583,`content_loc8` = '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE `skyfire_string`.`entry` = 583;
UPDATE `skyfire_string` SET `entry` = 584,`content_loc8` = 'Событие не найдено!' WHERE `skyfire_string`.`entry` = 584;
UPDATE `skyfire_string` SET `entry` = 585,`content_loc8` = 'События не существует!' WHERE `skyfire_string`.`entry` = 585;
UPDATE `skyfire_string` SET `entry` = 586,`content_loc8` = 'Событие %u: %s%s Начало: %s Конец: %s Время до повтора: %s Длина: %s Следующий раз будет в: %s' WHERE `skyfire_string`.`entry` = 586;
UPDATE `skyfire_string` SET `entry` = 587,`content_loc8` = 'Событие %u уже активно!' WHERE `skyfire_string`.`entry` = 587;
UPDATE `skyfire_string` SET `entry` = 588,`content_loc8` = 'Событие %u ещё не активно!' WHERE `skyfire_string`.`entry` = 588;
UPDATE `skyfire_string` SET `entry` = 592,`content_loc8` = 'Вы выучили все умения в профессии: %s' WHERE `skyfire_string`.`entry` = 592;
UPDATE `skyfire_string` SET `entry` = 593,`content_loc8` = 'Текущие забаненные аккаунты:' WHERE `skyfire_string`.`entry` = 593;
UPDATE `skyfire_string` SET `entry` = 594,`content_loc8` = '|    Аккаунт    |   Дата бана    |   Дата разбана  |  Кем забанен    |   Причина  |' WHERE `skyfire_string`.`entry` = 594;
UPDATE `skyfire_string` SET `entry` = 595,`content_loc8` = 'Текущие забаненные IP:' WHERE `skyfire_string`.`entry` = 595;
UPDATE `skyfire_string` SET `entry` = 596,`content_loc8` = '|      IP       |   Дата бана    |   Дата разбана  |  Кем забанен    |   Причина  |' WHERE `skyfire_string`.`entry` = 596;
UPDATE `skyfire_string` SET `entry` = 597,`content_loc8` = 'Текущие ГМ:' WHERE `skyfire_string`.`entry` = 597;
UPDATE `skyfire_string` SET `entry` = 598,`content_loc8` = '|    Аккаунт    |  ГМ  |' WHERE `skyfire_string`.`entry` = 598;
UPDATE `skyfire_string` SET `entry` = 599,`content_loc8` = 'Нет игровых мастеров.' WHERE `skyfire_string`.`entry` = 599;
UPDATE `skyfire_string` SET `entry` = 600,`content_loc8` = 'Альянс победил!' WHERE `skyfire_string`.`entry` = 600;
UPDATE `skyfire_string` SET `entry` = 601,`content_loc8` = 'Орда победила!' WHERE `skyfire_string`.`entry` = 601;
UPDATE `skyfire_string` SET `entry` = 602,`content_loc8` = 'Битва за Ущелье Песни Войны начнется через 1 минуту.' WHERE `skyfire_string`.`entry` = 602;
UPDATE `skyfire_string` SET `entry` = 603,`content_loc8` = 'Битва за Ущелье Песни Войны начнется через 30 секунд. Приготовьтесь!' WHERE `skyfire_string`.`entry` = 603;
UPDATE `skyfire_string` SET `entry` = 604,`content_loc8` = 'Битва за Ущелье Песни Войны началась!' WHERE `skyfire_string`.`entry` = 604;
UPDATE `skyfire_string` SET `entry` = 605,`content_loc8` = '$n захватил(а) флаг Орды!' WHERE `skyfire_string`.`entry` = 605;
UPDATE `skyfire_string` SET `entry` = 606,`content_loc8` = '$n захватил(а) флаг Альянса!' WHERE `skyfire_string`.`entry` = 606;
UPDATE `skyfire_string` SET `entry` = 607,`content_loc8` = '$n потерял(а) флаг Орды!' WHERE `skyfire_string`.`entry` = 607;
UPDATE `skyfire_string` SET `entry` = 608,`content_loc8` = '$n потерял(а) флаг Альянса!' WHERE `skyfire_string`.`entry` = 608;
UPDATE `skyfire_string` SET `entry` = 609,`content_loc8` = '$n вернул(а) флаг Альянса на свою базу!' WHERE `skyfire_string`.`entry` = 609;
UPDATE `skyfire_string` SET `entry` = 610,`content_loc8` = '$n вернул(а) флаг Орды на свою базу!' WHERE `skyfire_string`.`entry` = 610;
UPDATE `skyfire_string` SET `entry` = 611,`content_loc8` = '$n подобрал(а) флаг Орды!' WHERE `skyfire_string`.`entry` = 611;
UPDATE `skyfire_string` SET `entry` = 612,`content_loc8` = '$n подобрал(а) флаг Альянса!' WHERE `skyfire_string`.`entry` = 612;
UPDATE `skyfire_string` SET `entry` = 613,`content_loc8` = 'Флаги расположены по своим базам.' WHERE `skyfire_string`.`entry` = 613;
UPDATE `skyfire_string` SET `entry` = 614,`content_loc8` = 'Флаг Альянса теперь расположен на своей базе.' WHERE `skyfire_string`.`entry` = 614;
UPDATE `skyfire_string` SET `entry` = 615,`content_loc8` = 'Флаг Орды теперь расположен на своей базе.' WHERE `skyfire_string`.`entry` = 615;
UPDATE `skyfire_string` SET `entry` = 636,`content_loc8` = 'Битва за Око Бури начнется через 1 минуту.' WHERE `skyfire_string`.`entry` = 636;
UPDATE `skyfire_string` SET `entry` = 637,`content_loc8` = 'Битва за Око Бури начнется через 30 секунд.' WHERE `skyfire_string`.`entry` = 637;
UPDATE `skyfire_string` SET `entry` = 638,`content_loc8` = 'Битва за Око Бури началась!' WHERE `skyfire_string`.`entry` = 638;
UPDATE `skyfire_string` SET `entry` = 650,`content_loc8` = 'Орда захватила стойла!' WHERE `skyfire_string`.`entry` = 650;
UPDATE `skyfire_string` SET `entry` = 651,`content_loc8` = 'Альянс захватил ферму!' WHERE `skyfire_string`.`entry` = 651;
UPDATE `skyfire_string` SET `entry` = 652,`content_loc8` = 'Орда захватила ферму!' WHERE `skyfire_string`.`entry` = 652;
UPDATE `skyfire_string` SET `entry` = 653,`content_loc8` = 'Альянс захватил лесопилку!' WHERE `skyfire_string`.`entry` = 653;
UPDATE `skyfire_string` SET `entry` = 654,`content_loc8` = 'Орда захватила лесопилку!' WHERE `skyfire_string`.`entry` = 654;
UPDATE `skyfire_string` SET `entry` = 655,`content_loc8` = 'Альянс захватил кузницу!' WHERE `skyfire_string`.`entry` = 655;
UPDATE `skyfire_string` SET `entry` = 656,`content_loc8` = 'Орда захватила кузницу!' WHERE `skyfire_string`.`entry` = 656;
UPDATE `skyfire_string` SET `entry` = 657,`content_loc8` = 'Альянс захватил золотой рудник!' WHERE `skyfire_string`.`entry` = 657;
UPDATE `skyfire_string` SET `entry` = 658,`content_loc8` = 'Орда захватила золотой рудник!' WHERE `skyfire_string`.`entry` = 658;
UPDATE `skyfire_string` SET `entry` = 659,`content_loc8` = '$N осадил(а) стойла!' WHERE `skyfire_string`.`entry` = 659;
UPDATE `skyfire_string` SET `entry` = 660,`content_loc8` = '$N осадил(а) ферму!' WHERE `skyfire_string`.`entry` = 660;
UPDATE `skyfire_string` SET `entry` = 661,`content_loc8` = 'Битва за Низину Арати начнется через 1 минуту!' WHERE `skyfire_string`.`entry` = 661;
UPDATE `skyfire_string` SET `entry` = 662,`content_loc8` = 'Битва за Низину Арати начнется через 30 секунд.' WHERE `skyfire_string`.`entry` = 662;
UPDATE `skyfire_string` SET `entry` = 663,`content_loc8` = 'Битва за Низину Арати началась!' WHERE `skyfire_string`.`entry` = 663;
UPDATE `skyfire_string` SET `entry` = 664,`content_loc8` = 'Альянс собрал $1776W ресурсов и близок к победе!' WHERE `skyfire_string`.`entry` = 664;
UPDATE `skyfire_string` SET `entry` = 665,`content_loc8` = 'Орда собрала $1776W ресурсов и близка к победе!' WHERE `skyfire_string`.`entry` = 665;
UPDATE `skyfire_string` SET `entry` = 666,`content_loc8` = 'После вашей последней битвы в %s наградить вас Маркой Чести не удалось. В приложении к письму, вы можете обнаружить Марку Чести, которую мы не смогли доставить вам сразу. Спасибо за битву в %s!' WHERE `skyfire_string`.`entry` = 666;
UPDATE `skyfire_string` SET `entry` = 667,`content_loc8` = 'Альянс захватил Башню Магов!' WHERE `skyfire_string`.`entry` = 667;
UPDATE `skyfire_string` SET `entry` = 668,`content_loc8` = 'Орда захватила Башню Магов!' WHERE `skyfire_string`.`entry` = 668;
UPDATE `skyfire_string` SET `entry` = 669,`content_loc8` = 'Альянс захватил Дренейские Руины!' WHERE `skyfire_string`.`entry` = 669;
UPDATE `skyfire_string` SET `entry` = 670,`content_loc8` = 'Орда захватила Дренейские Руины!' WHERE `skyfire_string`.`entry` = 670;
UPDATE `skyfire_string` SET `entry` = 671,`content_loc8` = 'Альянс захватил Башню Эльфов Крови!' WHERE `skyfire_string`.`entry` = 671;
UPDATE `skyfire_string` SET `entry` = 672,`content_loc8` = 'Орда захватила Башню Эльфов Крови!' WHERE `skyfire_string`.`entry` = 672;
UPDATE `skyfire_string` SET `entry` = 673,`content_loc8` = 'Альянс захватил Обломки Сквернобота!' WHERE `skyfire_string`.`entry` = 673;
UPDATE `skyfire_string` SET `entry` = 674,`content_loc8` = 'Орда захватила Обломки Сквернобота!' WHERE `skyfire_string`.`entry` = 674;
UPDATE `skyfire_string` SET `entry` = 675,`content_loc8` = 'Альянс утратил контроль над Башней Магов!' WHERE `skyfire_string`.`entry` = 675;
UPDATE `skyfire_string` SET `entry` = 676,`content_loc8` = 'Орда утратила контроль над Башней Магов!' WHERE `skyfire_string`.`entry` = 676;
UPDATE `skyfire_string` SET `entry` = 677,`content_loc8` = 'Альянс утратил контроль над Дренейскими Руинами!' WHERE `skyfire_string`.`entry` = 677;
UPDATE `skyfire_string` SET `entry` = 678,`content_loc8` = 'Орда утратила контроль над Дренейскими Руинами!' WHERE `skyfire_string`.`entry` = 678;
UPDATE `skyfire_string` SET `entry` = 679,`content_loc8` = 'Альянс утратил контроль над Башней Эльфов Крови!' WHERE `skyfire_string`.`entry` = 679;
UPDATE `skyfire_string` SET `entry` = 680,`content_loc8` = 'Орда утратила контроль над Башней Эльфов Крови!' WHERE `skyfire_string`.`entry` = 680;
UPDATE `skyfire_string` SET `entry` = 681,`content_loc8` = 'Альянс утратил контроль над Обломками Сквернобота!' WHERE `skyfire_string`.`entry` = 681;
UPDATE `skyfire_string` SET `entry` = 682,`content_loc8` = 'Орда утратила контроль над Обломками Сквернобота!' WHERE `skyfire_string`.`entry` = 682;
UPDATE `skyfire_string` SET `entry` = 683,`content_loc8` = '%s захватывает флаг!' WHERE `skyfire_string`.`entry` = 683;
UPDATE `skyfire_string` SET `entry` = 684,`content_loc8` = 'Альянс захватил флаг!' WHERE `skyfire_string`.`entry` = 684;
UPDATE `skyfire_string` SET `entry` = 685,`content_loc8` = 'Орда захватила флаг!' WHERE `skyfire_string`.`entry` = 685;
UPDATE `skyfire_string` SET `entry` = 686,`content_loc8` = 'Флаг уронили!' WHERE `skyfire_string`.`entry` = 686;
UPDATE `skyfire_string` SET `entry` = 687,`content_loc8` = 'Флаг возвращен на базу.' WHERE `skyfire_string`.`entry` = 687;
UPDATE `skyfire_string` SET `entry` = 700,`content_loc8` = 'Вы должны иметь уровень %u,чтобы создать команду арены' WHERE `skyfire_string`.`entry` = 700;
UPDATE `skyfire_string` SET `entry` = 701,`content_loc8` = '1 минута до начала боя на арене!' WHERE `skyfire_string`.`entry` = 701;
UPDATE `skyfire_string` SET `entry` = 702,`content_loc8` = '30 секунд до начала боя на арене!' WHERE `skyfire_string`.`entry` = 702;
UPDATE `skyfire_string` SET `entry` = 703,`content_loc8` = '15 секунд до начала боя на арене!' WHERE `skyfire_string`.`entry` = 703;
UPDATE `skyfire_string` SET `entry` = 704,`content_loc8` = 'Бой на арене начинается!' WHERE `skyfire_string`.`entry` = 704;
UPDATE `skyfire_string` SET `entry` = 705,`content_loc8` = 'Вы должны подождать %s , чтобы начать говорить снова.' WHERE `skyfire_string`.`entry` = 705;
UPDATE `skyfire_string` SET `entry` = 706,`content_loc8` = 'Эта вещь имеет проблемы с одеванием/сохранением в сумке.' WHERE `skyfire_string`.`entry` = 706;
UPDATE `skyfire_string` SET `entry` = 707,`content_loc8` = 'Вы не можете этого сделать.' WHERE `skyfire_string`.`entry` = 707;
UPDATE `skyfire_string` SET `entry` = 708,`content_loc8` = '%s отошел: %s' WHERE `skyfire_string`.`entry` = 708;
UPDATE `skyfire_string` SET `entry` = 709,`content_loc8` = 'Не беспокоить' WHERE `skyfire_string`.`entry` = 709;
UPDATE `skyfire_string` SET `entry` = 710,`content_loc8` = 'Ваша группа содержит игроков, не состоящих в вашей команде арены. Перегруппируйтесь и попробуйте снова.' WHERE `skyfire_string`.`entry` = 710;
UPDATE `skyfire_string` SET `entry` = 711,`content_loc8` = 'Состояние очереди для %s (Уровень: с %u до %u)\r\nАльянса в очереди: %u (Нужно еще %u)\r\nОрды в очереди: %u (Нужно еще %u)' WHERE `skyfire_string`.`entry` = 711;
UPDATE `skyfire_string` SET `entry` = 712,`content_loc8` = '|cffff0000[Анонс БГ]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE `skyfire_string`.`entry` = 712;
UPDATE `skyfire_string` SET `entry` = 713,`content_loc8` = 'Вы должны быть %u уровня, чтобы присоединиться к арена команде!' WHERE `skyfire_string`.`entry` = 713;
UPDATE `skyfire_string` SET `entry` = 715,`content_loc8` = 'У вас недостаточно высокий уровень для этого поля боя' WHERE `skyfire_string`.`entry` = 715;
UPDATE `skyfire_string` SET `entry` = 717,`content_loc8` = '|cffff0000[Анонс БГ]:|r %s -- [%u-%u] Начинается!|r' WHERE `skyfire_string`.`entry` = 717;
UPDATE `skyfire_string` SET `entry` = 718,`content_loc8` = '|cffff0000[Анонс БГ]:|r %s -- Присоединились : %ux%u : %u|r' WHERE `skyfire_string`.`entry` = 718;
UPDATE `skyfire_string` SET `entry` = 719,`content_loc8` = '|cffff0000[Анонс БГ]:|r %s -- Вышли : %ux%u : %u|r' WHERE `skyfire_string`.`entry` = 719;
UPDATE `skyfire_string` SET `entry` = 720,`content_loc8` = 'Ваша группа слишком большая для этого поля боя. Пожалуйста, перегруппируйтесь и попробуйте снова.' WHERE `skyfire_string`.`entry` = 720;
UPDATE `skyfire_string` SET `entry` = 721,`content_loc8` = 'Ваша группа слишком большая для этой арены. Пожалуйста, перегруппируйтесь и попробуйте снова.' WHERE `skyfire_string`.`entry` = 721;
UPDATE `skyfire_string` SET `entry` = 722,`content_loc8` = 'Ваша группа содержит игроков, которых нет в вашей команде. Пожалуйста, перегруппируйтесь и попробуйте снова.' WHERE `skyfire_string`.`entry` = 722;
UPDATE `skyfire_string` SET `entry` = 723,`content_loc8` = 'Ваша группа содержит недостаточно игроков, чтобы присоединиться к этому матчу.' WHERE `skyfire_string`.`entry` = 723;
UPDATE `skyfire_string` SET `entry` = 724,`content_loc8` = 'Золотая команда выиграла!' WHERE `skyfire_string`.`entry` = 724;
UPDATE `skyfire_string` SET `entry` = 725,`content_loc8` = 'Зеленая команда выиграла!' WHERE `skyfire_string`.`entry` = 725;
UPDATE `skyfire_string` SET `entry` = 726,`content_loc8` = 'На этом поле боя недостаточно игроков. Оно закончится, если другие игроки не присоединятся к битве.' WHERE `skyfire_string`.`entry` = 726;
UPDATE `skyfire_string` SET `entry` = 727,`content_loc8` = 'В вашей группе имеется игрок, которого нет в игре. Удалите его и попробуйте снова.' WHERE `skyfire_string`.`entry` = 727;
UPDATE `skyfire_string` SET `entry` = 728,`content_loc8` = 'Ваша группа имеет игроков из враждующей фракции. Вы не можете встать в очередь на поле битвы группой.' WHERE `skyfire_string`.`entry` = 728;
UPDATE `skyfire_string` SET `entry` = 729,`content_loc8` = 'Ваша группа имеет игроков из разных разрядов по уровню. Вы не можете встать в очередь группой.' WHERE `skyfire_string`.`entry` = 729;
UPDATE `skyfire_string` SET `entry` = 730,`content_loc8` = 'Кто-то из вашей группы уже находиться в очереди на это поле битвы. Ему(ей) нужно выйти, перед присоединением группой.' WHERE `skyfire_string`.`entry` = 730;
UPDATE `skyfire_string` SET `entry` = 731,`content_loc8` = 'Кто-то в вашей группе - Дезертир. Вы не можете присоединиться группой.' WHERE `skyfire_string`.`entry` = 731;
UPDATE `skyfire_string` SET `entry` = 732,`content_loc8` = 'Кто-то в вашей группе находится в очереди на три поля сражения. Вы не можете присоедениться группой.' WHERE `skyfire_string`.`entry` = 732;
UPDATE `skyfire_string` SET `entry` = 733,`content_loc8` = 'Вы не можете телепортировать игроков в зону сражения или на Арену.' WHERE `skyfire_string`.`entry` = 733;
UPDATE `skyfire_string` SET `entry` = 734,`content_loc8` = 'Вы не можете призывать игроков в зону сражения или на Арену.' WHERE `skyfire_string`.`entry` = 734;
UPDATE `skyfire_string` SET `entry` = 735,`content_loc8` = 'Вы должны быть в режиме ГМ,чтобы телепортироваться к игроку на поле битвы.' WHERE `skyfire_string`.`entry` = 735;
UPDATE `skyfire_string` SET `entry` = 736,`content_loc8` = 'Вы не можете телепортироваться с одной зоны сражений к другой. Пожалуйста, покиньте текущую зону битвы.' WHERE `skyfire_string`.`entry` = 736;
UPDATE `skyfire_string` SET `entry` = 737,`content_loc8` = 'Арены установлены в режим 1v1 для отладки. Не присоединяйтесь группой.' WHERE `skyfire_string`.`entry` = 737;
UPDATE `skyfire_string` SET `entry` = 738,`content_loc8` = 'Количество игроков на арену поставлено в нормальном режиме.' WHERE `skyfire_string`.`entry` = 738;
UPDATE `skyfire_string` SET `entry` = 739,`content_loc8` = 'Поля боя установлены в режим 1v0 для отладки.' WHERE `skyfire_string`.`entry` = 739;
UPDATE `skyfire_string` SET `entry` = 740,`content_loc8` = 'Количество игроков для полей боя поставлено в нормальный режим.' WHERE `skyfire_string`.`entry` = 740;
UPDATE `skyfire_string` SET `entry` = 741,`content_loc8` = 'Распределение арена очков в зависимости от рейтинга команд, это может занять несколько минут. Пожалуйста, подождите...' WHERE `skyfire_string`.`entry` = 741;
UPDATE `skyfire_string` SET `entry` = 742,`content_loc8` = 'Распределение арена очков для игрока...' WHERE `skyfire_string`.`entry` = 742;
UPDATE `skyfire_string` SET `entry` = 743,`content_loc8` = 'Конец обновления арена очков для всех персонажей в сети.' WHERE `skyfire_string`.`entry` = 743;
UPDATE `skyfire_string` SET `entry` = 744,`content_loc8` = 'Обновление онлайна, арена очков и др. для арена команд, обновление характеристик для игроков в сети...' WHERE `skyfire_string`.`entry` = 744;
UPDATE `skyfire_string` SET `entry` = 745,`content_loc8` = 'Модификация закончена.' WHERE `skyfire_string`.`entry` = 745;
UPDATE `skyfire_string` SET `entry` = 746,`content_loc8` = 'Закончен пересчет очков Арены.' WHERE `skyfire_string`.`entry` = 746;
UPDATE `skyfire_string` SET `entry` = 750,`content_loc8` = 'Недостаточно игроков. Игра будет закрыта через %u минут(ы).' WHERE `skyfire_string`.`entry` = 750;
UPDATE `skyfire_string` SET `entry` = 751,`content_loc8` = 'Недостаточно игроков. Игра будет закрыта через %u секунд(ы).' WHERE `skyfire_string`.`entry` = 751;
UPDATE `skyfire_string` SET `entry` = 753,`content_loc8` = 'Сражение в Ущелье Песни Войны начнется через 2 минуты' WHERE `skyfire_string`.`entry` = 753;
UPDATE `skyfire_string` SET `entry` = 754,`content_loc8` = 'Сражение в Низине Арати начнется через 2 минуты.' WHERE `skyfire_string`.`entry` = 754;
UPDATE `skyfire_string` SET `entry` = 755,`content_loc8` = 'Сражение в Око Бури начнется через 2 минуты.' WHERE `skyfire_string`.`entry` = 755;
UPDATE `skyfire_string` SET `entry` = 785,`content_loc8` = 'Тест Арены %s' WHERE `skyfire_string`.`entry` = 785;
UPDATE `skyfire_string` SET `entry` = 786,`content_loc8` = '|cffff0000[Авто-объявление]:|r' WHERE `skyfire_string`.`entry` = 786;
UPDATE `skyfire_string` SET `entry` = 800,`content_loc8` = 'Неправильное имя' WHERE `skyfire_string`.`entry` = 800;
UPDATE `skyfire_string` SET `entry` = 801,`content_loc8` = 'У вас недостаточно денег' WHERE `skyfire_string`.`entry` = 801;
UPDATE `skyfire_string` SET `entry` = 802,`content_loc8` = 'У вас недостаточно места в рюкзаке' WHERE `skyfire_string`.`entry` = 802;
UPDATE `skyfire_string` SET `entry` = 803,`content_loc8` = 'У вашего напарника недостаточно места в рюкзаке' WHERE `skyfire_string`.`entry` = 803;
UPDATE `skyfire_string` SET `entry` = 804,`content_loc8` = 'У вас нет для этого прав' WHERE `skyfire_string`.`entry` = 804;
UPDATE `skyfire_string` SET `entry` = 805,`content_loc8` = 'Неизвестный язык' WHERE `skyfire_string`.`entry` = 805;
UPDATE `skyfire_string` SET `entry` = 806,`content_loc8` = 'Вы не знаете этот язык' WHERE `skyfire_string`.`entry` = 806;
UPDATE `skyfire_string` SET `entry` = 807,`content_loc8` = 'Напишите имя персонажа' WHERE `skyfire_string`.`entry` = 807;
UPDATE `skyfire_string` SET `entry` = 808,`content_loc8` = 'Игрок %s не найден или его нет в игре' WHERE `skyfire_string`.`entry` = 808;
UPDATE `skyfire_string` SET `entry` = 809,`content_loc8` = 'Аккаунт персонажа %s не найдён' WHERE `skyfire_string`.`entry` = 809;
UPDATE `skyfire_string` SET `entry` = 810,`content_loc8` = '|Hplayer:$N|h[$N]|h $gзаслужил:заслужила; достижение $a!' WHERE `skyfire_string`.`entry` = 810;
UPDATE `skyfire_string` SET `entry` = 811,`content_loc8` = 'Мастер гильдии' WHERE `skyfire_string`.`entry` = 811;
UPDATE `skyfire_string` SET `entry` = 812,`content_loc8` = 'Офицер' WHERE `skyfire_string`.`entry` = 812;
UPDATE `skyfire_string` SET `entry` = 813,`content_loc8` = 'Ветеран' WHERE `skyfire_string`.`entry` = 813;
UPDATE `skyfire_string` SET `entry` = 814,`content_loc8` = 'Участник' WHERE `skyfire_string`.`entry` = 814;
UPDATE `skyfire_string` SET `entry` = 815,`content_loc8` = 'Новичок' WHERE `skyfire_string`.`entry` = 815;
UPDATE `skyfire_string` SET `entry` = 816,`content_loc8` = 'Внимание: вы попали в зону, не предназначенную для полетов, и будете высажены со своего транспорта!' WHERE `skyfire_string`.`entry` = 816;
UPDATE `skyfire_string` SET `entry` = 1000,`content_loc8` = 'Завершение демона...' WHERE `skyfire_string`.`entry` = 1000;
UPDATE `skyfire_string` SET `entry` = 1001,`content_loc8` = 'Аккаунт: %s удален' WHERE `skyfire_string`.`entry` = 1001;
UPDATE `skyfire_string` SET `entry` = 1002,`content_loc8` = 'Аккаунт %s не может быть удалён (возможно формат sql файла был обновлён)' WHERE `skyfire_string`.`entry` = 1002;
UPDATE `skyfire_string` SET `entry` = 1003,`content_loc8` = 'Аккаунт %s не может быть удалён (неизвестная ошибка)' WHERE `skyfire_string`.`entry` = 1003;
UPDATE `skyfire_string` SET `entry` = 1004,`content_loc8` = 'Создана учетная запись:  %s' WHERE `skyfire_string`.`entry` = 1004;
UPDATE `skyfire_string` SET `entry` = 1005,`content_loc8` = 'Имя аккаунта не может содержать больше 16 символов (лимит клиента), аккаунт не создан!' WHERE `skyfire_string`.`entry` = 1005;
UPDATE `skyfire_string` SET `entry` = 1006,`content_loc8` = 'Аккаунт с таким именем уже существует!' WHERE `skyfire_string`.`entry` = 1006;
UPDATE `skyfire_string` SET `entry` = 1007,`content_loc8` = 'Аккаунт %s не может быть удалён (возможно формат sql файла был обновлён)' WHERE `skyfire_string`.`entry` = 1007;
UPDATE `skyfire_string` SET `entry` = 1008,`content_loc8` = 'Аккаунт %s не создан (неизвестная ошибка)' WHERE `skyfire_string`.`entry` = 1008;
UPDATE `skyfire_string` SET `entry` = 1009,`content_loc8` = 'Игрок %s (GUID: %u) Аккаунт %s (ID: %u) удалён.' WHERE `skyfire_string`.`entry` = 1009;
UPDATE `skyfire_string` SET `entry` = 1010,`content_loc8` = '|    Аккаунт    |       Персонаж      |       IP        | ГМ | Версия аддона |' WHERE `skyfire_string`.`entry` = 1010;
UPDATE `skyfire_string` SET `entry` = 1011,`content_loc8` = '|<Error>        | %20s |<Error>          |<Er>| <Error>   |' WHERE `skyfire_string`.`entry` = 1011;
UPDATE `skyfire_string` SET `entry` = 1012,`content_loc8` = '===========================================================================' WHERE `skyfire_string`.`entry` = 1012;
UPDATE `skyfire_string` SET `entry` = 1013,`content_loc8` = '|%15s| %20s | %15s |%4d| %9d |' WHERE `skyfire_string`.`entry` = 1013;
UPDATE `skyfire_string` SET `entry` = 1014,`content_loc8` = 'Нет игроков онлайн.' WHERE `skyfire_string`.`entry` = 1014;
UPDATE `skyfire_string` SET `entry` = 1016,`content_loc8` = '| GUID       | Имя                   | Учетная запись           | Дата удаления   |' WHERE `skyfire_string`.`entry` = 1016;
UPDATE `skyfire_string` SET `entry` = 1019,`content_loc8` = 'Не найдено персонажей.' WHERE `skyfire_string`.`entry` = 1019;
UPDATE `skyfire_string` SET `entry` = 1020,`content_loc8` = 'Восстановление следующих персонажей:' WHERE `skyfire_string`.`entry` = 1020;
UPDATE `skyfire_string` SET `entry` = 1021,`content_loc8` = 'Удаление следующих персонажей:' WHERE `skyfire_string`.`entry` = 1021;
UPDATE `skyfire_string` SET `entry` = 1023,`content_loc8` = 'Персонаж ''%s'' (GUID: %u Учетная запись %u) не может быть восстановлен: учетная запись не существует!' WHERE `skyfire_string`.`entry` = 1023;
UPDATE `skyfire_string` SET `entry` = 1024,`content_loc8` = 'Персонаж ''%s'' (GUID: %u Учетная запись %u) не может быть восстановлен: создано максимальное количество персонажей на учетной записи!' WHERE `skyfire_string`.`entry` = 1024;
UPDATE `skyfire_string` SET `entry` = 1025,`content_loc8` = 'Персонаж ''%s'' (GUID: %u Учетная запись %u) не может быть восстановлен: новое имя уже используется!' WHERE `skyfire_string`.`entry` = 1025;
UPDATE `skyfire_string` SET `entry` = 1026,`content_loc8` = 'GUID: %u Имя: %s Учетная запись: %s (%u) Дата: %s' WHERE `skyfire_string`.`entry` = 1026;
UPDATE `skyfire_string` SET `entry` = 1100,`content_loc8` = 'Аккаунт %s (ID: %u) обновил до %u версию аддона игры.' WHERE `skyfire_string`.`entry` = 1100;
UPDATE `skyfire_string` SET `entry` = 1101,`content_loc8` = 'Сообщение дня изменено на:\r\n%s' WHERE `skyfire_string`.`entry` = 1101;
UPDATE `skyfire_string` SET `entry` = 1102,`content_loc8` = 'Сообщение отправлено игроку %s: %s' WHERE `skyfire_string`.`entry` = 1102;
UPDATE `skyfire_string` SET `entry` = 1103,`content_loc8` = '%d - %s %s' WHERE `skyfire_string`.`entry` = 1103;
UPDATE `skyfire_string` SET `entry` = 1104,`content_loc8` = '%d - %s' WHERE `skyfire_string`.`entry` = 1104;
UPDATE `skyfire_string` SET `entry` = 1105,`content_loc8` = '%d - %s' WHERE `skyfire_string`.`entry` = 1105;
UPDATE `skyfire_string` SET `entry` = 1106,`content_loc8` = '%d - %s %s' WHERE `skyfire_string`.`entry` = 1106;
UPDATE `skyfire_string` SET `entry` = 1107,`content_loc8` = '%d - %s' WHERE `skyfire_string`.`entry` = 1107;
UPDATE `skyfire_string` SET `entry` = 1108,`content_loc8` = '%d - %s %s' WHERE `skyfire_string`.`entry` = 1108;
UPDATE `skyfire_string` SET `entry` = 1109,`content_loc8` = '%d - %s %s %s %s' WHERE `skyfire_string`.`entry` = 1109;
UPDATE `skyfire_string` SET `entry` = 1110,`content_loc8` = '%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE `skyfire_string`.`entry` = 1110;
UPDATE `skyfire_string` SET `entry` = 1111,`content_loc8` = '%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE `skyfire_string`.`entry` = 1111;
UPDATE `skyfire_string` SET `entry` = 1112,`content_loc8` = 'Ошибка при открытии файла: %s' WHERE `skyfire_string`.`entry` = 1112;
UPDATE `skyfire_string` SET `entry` = 1113,`content_loc8` = 'Аккаунт %s (%u) имеет максимальное количество персонажей (лимит клиента)' WHERE `skyfire_string`.`entry` = 1113;
UPDATE `skyfire_string` SET `entry` = 1114,`content_loc8` = 'Dump-файл повреждён!' WHERE `skyfire_string`.`entry` = 1114;
UPDATE `skyfire_string` SET `entry` = 1115,`content_loc8` = 'Неправильное имя персонажа!' WHERE `skyfire_string`.`entry` = 1115;
UPDATE `skyfire_string` SET `entry` = 1116,`content_loc8` = 'Неправильный GUID персонажа!' WHERE `skyfire_string`.`entry` = 1116;
UPDATE `skyfire_string` SET `entry` = 1117,`content_loc8` = 'GUID %u персонажа используется!' WHERE `skyfire_string`.`entry` = 1117;
UPDATE `skyfire_string` SET `entry` = 1118,`content_loc8` = '%d - guild: %s (guid: %u) %s' WHERE `skyfire_string`.`entry` = 1118;
UPDATE `skyfire_string` SET `entry` = 1119,`content_loc8` = 'Вы должны использовать мужской или женский пол.' WHERE `skyfire_string`.`entry` = 1119;
UPDATE `skyfire_string` SET `entry` = 1120,`content_loc8` = 'Вы сменили пол с %s на %s.' WHERE `skyfire_string`.`entry` = 1120;
UPDATE `skyfire_string` SET `entry` = 1121,`content_loc8` = 'Ваш пол сменён на %s  %s.' WHERE `skyfire_string`.`entry` = 1121;
UPDATE `skyfire_string` SET `entry` = 1122,`content_loc8` = '(%u/%u +постоянный %u +временный %u)' WHERE `skyfire_string`.`entry` = 1122;
UPDATE `skyfire_string` SET `entry` = 1123,`content_loc8` = 'Питомец не найден' WHERE `skyfire_string`.`entry` = 1123;
UPDATE `skyfire_string` SET `entry` = 1124,`content_loc8` = 'Неверный тип питомца' WHERE `skyfire_string`.`entry` = 1124;
UPDATE `skyfire_string` SET `entry` = 1125,`content_loc8` = 'Ваш питомец выучил все таланты.' WHERE `skyfire_string`.`entry` = 1125;
UPDATE `skyfire_string` SET `entry` = 1126,`content_loc8` = 'Таланты Вашего питомца были сброшены.' WHERE `skyfire_string`.`entry` = 1126;
UPDATE `skyfire_string` SET `entry` = 1127,`content_loc8` = 'Таланты для %s питомца сброшены' WHERE `skyfire_string`.`entry` = 1127;
UPDATE `skyfire_string` SET `entry` = 1128,`content_loc8` = '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE `skyfire_string`.`entry` = 1128;
UPDATE `skyfire_string` SET `entry` = 1129,`content_loc8` = '%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE `skyfire_string`.`entry` = 1129;
UPDATE `skyfire_string` SET `entry` = 1200,`content_loc8` = 'Вы пытаетесь просмотреть ролик %u, но он не существует.' WHERE `skyfire_string`.`entry` = 1200;
UPDATE `skyfire_string` SET `entry` = 1201,`content_loc8` = 'Вы пытаетесь просмотреть ролик %u, но он не существует.' WHERE `skyfire_string`.`entry` = 1201;
UPDATE `skyfire_string` SET `entry` = 1300,`content_loc8` = 'Альянс' WHERE `skyfire_string`.`entry` = 1300;
UPDATE `skyfire_string` SET `entry` = 1301,`content_loc8` = 'Орда' WHERE `skyfire_string`.`entry` = 1301;
UPDATE `skyfire_string` SET `entry` = 1302,`content_loc8` = '%s разрушена %s!' WHERE `skyfire_string`.`entry` = 1302;
UPDATE `skyfire_string` SET `entry` = 1303,`content_loc8` = '%s атакуют! Если не помешат, %s разрушит это!' WHERE `skyfire_string`.`entry` = 1303;
UPDATE `skyfire_string` SET `entry` = 1304,`content_loc8` = 'NULL' WHERE `skyfire_string`.`entry` = 1304;
UPDATE `skyfire_string` SET `entry` = 1326,`content_loc8` = 'Сражение на Альтеракской долине начнется через 1 минуту.' WHERE `skyfire_string`.`entry` = 1326;
UPDATE `skyfire_string` SET `entry` = 1327,`content_loc8` = 'Сражение на Альтеракской долине начнется через 30 секунд. Приготовьтесь!' WHERE `skyfire_string`.`entry` = 1327;
UPDATE `skyfire_string` SET `entry` = 1328,`content_loc8` = 'Сражение на Альтеракской долине началось!' WHERE `skyfire_string`.`entry` = 1328;
UPDATE `skyfire_string` SET `entry` = 1333,`content_loc8` = 'Сражение на Альтеракской долине начнется через 2 минуты.' WHERE `skyfire_string`.`entry` = 1333;
UPDATE `skyfire_string` SET `entry` = 2000,`content_loc8` = '|cff00ff00Новый запрос от|r|cffff00ff %s.|r |cff00ff00Содержание запроса:|r|cffff00ff %d.|r' WHERE `skyfire_string`.`entry` = 2000;
UPDATE `skyfire_string` SET `entry` = 2001,`content_loc8` = '|cff00ff00Игрок|r|cffff00ff %s |r|cff00ff00изменил свой запрос:|r|cffff00ff %d.|r' WHERE `skyfire_string`.`entry` = 2001;
UPDATE `skyfire_string` SET `entry` = 2002,`content_loc8` = '|cff00ff00Игрок|r|cffff00ff %s |r|cff00ff00отменил запрос:|r|cffff00ff %d.|r' WHERE `skyfire_string`.`entry` = 2002;
UPDATE `skyfire_string` SET `entry` = 2003,`content_loc8` = '|cff00ff00Закрыто|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2003;
UPDATE `skyfire_string` SET `entry` = 2004,`content_loc8` = '|cff00ff00Удалено|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2004;
UPDATE `skyfire_string` SET `entry` = 2005,`content_loc8` = 'Запрос не найден.' WHERE `skyfire_string`.`entry` = 2005;
UPDATE `skyfire_string` SET `entry` = 2006,`content_loc8` = 'Пожайлуста, закройте запрос перед удалением.' WHERE `skyfire_string`.`entry` = 2006;
UPDATE `skyfire_string` SET `entry` = 2007,`content_loc8` = 'Запрос %d уже прикреплен.' WHERE `skyfire_string`.`entry` = 2007;
UPDATE `skyfire_string` SET `entry` = 2008,`content_loc8` = '%u запросов успешно перезагруженно из базы данных.' WHERE `skyfire_string`.`entry` = 2008;
UPDATE `skyfire_string` SET `entry` = 2009,`content_loc8` = 'Отображение списка открытых запросов.' WHERE `skyfire_string`.`entry` = 2009;
UPDATE `skyfire_string` SET `entry` = 2010,`content_loc8` = 'Отображение списка открытых запросов от игроков, которые в сети.' WHERE `skyfire_string`.`entry` = 2010;
UPDATE `skyfire_string` SET `entry` = 2011,`content_loc8` = 'Отображение списка закрытых запросов.' WHERE `skyfire_string`.`entry` = 2011;
UPDATE `skyfire_string` SET `entry` = 2012,`content_loc8` = 'Указано неправильное имя. Имя должно соответствовать любому ГМ, который находится в сети.' WHERE `skyfire_string`.`entry` = 2012;
UPDATE `skyfire_string` SET `entry` = 2013,`content_loc8` = 'Запрос уже прикреплен к этому ГМу. Чтобы открепить запрос используйте команду .ticket unassign %d и далее переназначьте.' WHERE `skyfire_string`.`entry` = 2013;
UPDATE `skyfire_string` SET `entry` = 2014,`content_loc8` = 'Запрос %d не прикреплен к кому-либо, вы не можете открепить его.' WHERE `skyfire_string`.`entry` = 2014;
UPDATE `skyfire_string` SET `entry` = 2015,`content_loc8` = 'Вы не можете откреплять запросы ГМам, у которых выше уровень доступа.' WHERE `skyfire_string`.`entry` = 2015;
UPDATE `skyfire_string` SET `entry` = 2016,`content_loc8` = 'Невозможно закрыть запрос %d, он прикреплен к другому ГМу.' WHERE `skyfire_string`.`entry` = 2016;
UPDATE `skyfire_string` SET `entry` = 2017,`content_loc8` = '|cff00ff00Запрос|r:|cff00ccff %d.|r ' WHERE `skyfire_string`.`entry` = 2017;
UPDATE `skyfire_string` SET `entry` = 2018,`content_loc8` = '|cff00ff00Создан от|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2018;
UPDATE `skyfire_string` SET `entry` = 2019,`content_loc8` = '|cff00ff00Последнее изменение|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2019;
UPDATE `skyfire_string` SET `entry` = 2020,`content_loc8` = '|cff00ff00Прикреплено к|r:|cff00ccff %s|r' WHERE `skyfire_string`.`entry` = 2020;
UPDATE `skyfire_string` SET `entry` = 2021,`content_loc8` = '|cff00ff00Откреплен|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2021;
UPDATE `skyfire_string` SET `entry` = 2022,`content_loc8` = '|cff00ff00Сообщение|r: "%s"|r ' WHERE `skyfire_string`.`entry` = 2022;
UPDATE `skyfire_string` SET `entry` = 2023,`content_loc8` = '|cff00ff00Комментарий|r: "%s"|r ' WHERE `skyfire_string`.`entry` = 2023;
UPDATE `skyfire_string` SET `entry` = 2024,`content_loc8` = '|cff00ccff%s|r |cff00ff00Добавлен комментарий|r: "%s"|r ' WHERE `skyfire_string`.`entry` = 2024;
UPDATE `skyfire_string` SET `entry` = 2025,`content_loc8` = '|cff00ff00Создан|r:|cff00ccff %s|r ' WHERE `skyfire_string`.`entry` = 2025;
UPDATE `skyfire_string` SET `entry` = 5000,`content_loc8` = 'Вы заморозили игрока %s.' WHERE `skyfire_string`.`entry` = 5000;
UPDATE `skyfire_string` SET `entry` = 5001,`content_loc8` = 'Это должно быть забавно, но нет... вы не можете заморозить себя!' WHERE `skyfire_string`.`entry` = 5001;
UPDATE `skyfire_string` SET `entry` = 5002,`content_loc8` = 'Неверно указано имя цели.' WHERE `skyfire_string`.`entry` = 5002;
UPDATE `skyfire_string` SET `entry` = 5003,`content_loc8` = 'Вы разморозили игрока %s.' WHERE `skyfire_string`.`entry` = 5003;
UPDATE `skyfire_string` SET `entry` = 5004,`content_loc8` = 'Нету замороженных игроков.' WHERE `skyfire_string`.`entry` = 5004;
UPDATE `skyfire_string` SET `entry` = 5005,`content_loc8` = 'Следующий игроки на сервере заморожены:' WHERE `skyfire_string`.`entry` = 5005;
UPDATE `skyfire_string` SET `entry` = 5006,`content_loc8` = '- %s' WHERE `skyfire_string`.`entry` = 5006;
UPDATE `skyfire_string` SET `entry` = 5007,`content_loc8` = 'Вы должны находиться в рейдовой группе чтобы войти в это подземелье.' WHERE `skyfire_string`.`entry` = 5007;
UPDATE `skyfire_string` SET `entry` = 5009,`content_loc8` = 'Звук %u прозвучал' WHERE `skyfire_string`.`entry` = 5009;
UPDATE `skyfire_string` SET `entry` = 5010,`content_loc8` = 'GUID ссылки: %u, Entry: %u (%s)' WHERE `skyfire_string`.`entry` = 5010;
UPDATE `skyfire_string` SET `entry` = 5011,`content_loc8` = 'Вы не можете телепортироваться к себе!' WHERE `skyfire_string`.`entry` = 5011;
UPDATE `skyfire_string` SET `entry` = 5012,`content_loc8` = 'Карты не найдены!' WHERE `skyfire_string`.`entry` = 5012;
UPDATE `skyfire_string` SET `entry` = 5013,`content_loc8` = '[Континент]' WHERE `skyfire_string`.`entry` = 5013;
UPDATE `skyfire_string` SET `entry` = 5014,`content_loc8` = '[Подземелье]' WHERE `skyfire_string`.`entry` = 5014;
UPDATE `skyfire_string` SET `entry` = 5015,`content_loc8` = '[Поле битвы]' WHERE `skyfire_string`.`entry` = 5015;
UPDATE `skyfire_string` SET `entry` = 5016,`content_loc8` = '[Арена]' WHERE `skyfire_string`.`entry` = 5016;
UPDATE `skyfire_string` SET `entry` = 5017,`content_loc8` = '[Время сброса рейдового подземелья: %s]' WHERE `skyfire_string`.`entry` = 5017;
UPDATE `skyfire_string` SET `entry` = 5018,`content_loc8` = '[Время сброса героического подземелья: %s]' WHERE `skyfire_string`.`entry` = 5018;
UPDATE `skyfire_string` SET `entry` = 5019,`content_loc8` = '[Возможно применение транспорта]' WHERE `skyfire_string`.`entry` = 5019;
UPDATE `skyfire_string` SET `entry` = 6613,`content_loc8` = '|cfff00000[ГМ объявление]: %s|r' WHERE `skyfire_string`.`entry` = 6613;
UPDATE `skyfire_string` SET `entry` = 6614,`content_loc8` = 'Уведомление ГМам - ' WHERE `skyfire_string`.`entry` = 6614;
UPDATE `skyfire_string` SET `entry` = 6616,`content_loc8` = 'Выключены личные сообщения у %s' WHERE `skyfire_string`.`entry` = 6616;
UPDATE `skyfire_string` SET `entry` = 7523,`content_loc8` = 'Мир: запрещение соединений.' WHERE `skyfire_string`.`entry` = 7523;
UPDATE `skyfire_string` SET `entry` = 7524,`content_loc8` = 'Мир: разрешение соединений.' WHERE `skyfire_string`.`entry` = 7524;
UPDATE `skyfire_string` SET `entry` = 10001,`content_loc8` = 'Орда захватила Дозорное укрепление!' WHERE `skyfire_string`.`entry` = 10001;
UPDATE `skyfire_string` SET `entry` = 10002,`content_loc8` = 'Альянс захватил Дозорное укрепление!' WHERE `skyfire_string`.`entry` = 10002;
UPDATE `skyfire_string` SET `entry` = 10003,`content_loc8` = 'Орда захватила Ристалище!' WHERE `skyfire_string`.`entry` = 10003;
UPDATE `skyfire_string` SET `entry` = 10004,`content_loc8` = 'Альянс захватил Ристалище!' WHERE `skyfire_string`.`entry` = 10004;
UPDATE `skyfire_string` SET `entry` = 10005,`content_loc8` = 'Орда захватила Изрезанный холм!' WHERE `skyfire_string`.`entry` = 10005;
UPDATE `skyfire_string` SET `entry` = 10006,`content_loc8` = 'Альянс захватил Изрезанный холм!' WHERE `skyfire_string`.`entry` = 10006;
UPDATE `skyfire_string` SET `entry` = 10007,`content_loc8` = 'Орда потеряла Дозорное укрепление!' WHERE `skyfire_string`.`entry` = 10007;
UPDATE `skyfire_string` SET `entry` = 10008,`content_loc8` = 'Альянс потерял Дозорное укрепление!' WHERE `skyfire_string`.`entry` = 10008;
UPDATE `skyfire_string` SET `entry` = 10009,`content_loc8` = 'Орда потеряла Ристалище!' WHERE `skyfire_string`.`entry` = 10009;
UPDATE `skyfire_string` SET `entry` = 10010,`content_loc8` = 'Альянс потерял Ристалище!' WHERE `skyfire_string`.`entry` = 10010;
UPDATE `skyfire_string` SET `entry` = 10011,`content_loc8` = 'Орда потеряла Изрезанный холм!' WHERE `skyfire_string`.`entry` = 10011;
UPDATE `skyfire_string` SET `entry` = 10012,`content_loc8` = 'Альянс потерял Изрезанный холм!' WHERE `skyfire_string`.`entry` = 10012;
UPDATE `skyfire_string` SET `entry` = 11000,`content_loc8` = '|cffffff00[|c00077766Авто-объявление|cffffff00]: |cFFF222FF%s|r' WHERE `skyfire_string`.`entry` = 11000;
